- docs/en/reference/basic-mapping.rst
- docs/en/reference/console-commands.rst
- Fixes incorrect yaml namespace in `docs/en/reference/basic-mapping.rst`
- Adds new operator to object instantiation in ` docs/en/reference/console-commands.rst `
> [doc] Fix errors in sample code examples

- tests/Doctrine/ODM/MongoDB/Tests/Functional/FilesTest.php
- tests/Documents/File.php
This tests the File annotation example that was added in 621a4481c9fe8f71fc12fdd01ebd1f9d501f4381 for #1005.
> Functional test for NotSaved and GridFS metadata fields

- tests/Doctrine/ODM/MongoDB/Tests/Functional/BinDataTest.php
Driver 1.6+ validates that binary data for the RFC4122 sub-type is 16-bytes.
> Fix BinDataTest for driver 1.6+

- composer.json
Doctrine Common 2.5 is available, and the ODM should allow using it. Otherwise it makes it impossible to install it alongside the ORM 2.5 (which requires new features of Common 2.5)
> Allow to use uptodate versions of Doctrine Common

- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
Related discussion: https://github.com/doctrine/mongodb-odm/issues/225#issuecomment-63811609
Long story short ``SchemaManager`` needs ``targetDocument`` specified to go deeper while creating indexes. With this modification documents specified in ``discriminatorMap`` will also be checked for any indexes defined there.
cc @bensquire
> Consider discriminated Embeds in index generation

- lib/Doctrine/ODM/MongoDB/Tools/DocumentGenerator.php
Hi,
the generated type hint for the get method of collections in documents generated with odm:generate:documents was missing a backslash at the beginning. This made it impossible (out of the box) to autocomplete on such methods.
Unit tests passed, since there seem to be none.
Cheers
Marko
> added backslash to FQCN in DocumentGenerator

- lib/Doctrine/ODM/MongoDB/DocumentRepository.php
- tests/Doctrine/ODM/MongoDB/Tests/DocumentRepositoryTest.php
- tests/Documents/VersionedDocument.php
I have issue that some documents expire in mongodb and references return null.
Then $repository->find($invalidId, LockMode::OPTIMISTIC); throws exceptions when UnitOfWork tries to lock NULL.
> Lock document only if found

- docs/en/reference/annotations-reference.rst
As far as I remember ``strategy`` has no effect for ``@EmbedOne`` annotation (and it doesn't exist in corresponding Annotation definition) and example code was copied from ``@EmbedMany`` while its explaination was refering to totally different code
> [Docs] Fix @EmbedOne annotation reference

- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/AbstractDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.User.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/yaml/TestDocuments.User.dcm.yml
The Yaml and XML drivers currently do not implements the also load methods mapping. I personally only wanted the feature for the Yaml driver, but I've created a pull request implementing it for both Drivers, with updates to XML schema too. I did both at the same time for simplicity in adding the test below.
I've also extended the current AbstractDriverTest unit test and supporting fixtures to add in the new elements, and test they get set on the resulting ClassMetaData. I was unsure if this was the correct place to be testing this.
As a side note also, I think the current TestDocuments.User.dcm.xml fixture does not validate as correct XML in the tool I used, I think because the embed* and reference* elements are out of order compared to the schema. I didn't want to "fix" it, because a) I …
> Implement "also load methods" in Yaml and XML drivers.

- lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
This is a fix for the issue where dot syntax would not work in field-names to prime. 
https://github.com/doctrine/mongodb-odm/issues/624
With this fix, now you can prime a reference that is in an embedded document. It works no matter how many levels of embedded documents there are between the original document and the final reference, but it does not traverse across multiple references. 
The recursive method is based loosely upon the structure of the prepareQueryElement() method of Doctrine\ODM\MongoDB\Persisters\DocumentPersister, except with priming it can be much simpler since we only care if it's a reference or embedded document.
> Embedded priming fix for Issue #624, with Tests

- lib/Doctrine/ODM/MongoDB/Types/DateType.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DateTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Types/DateTypeTest.php
Fixes #1061 
Affects #1060 : now will overflow and the loaded date will be in 2036. Note that problem only appears when saving to and loading from Mongo, not when simply converting values.
Duplicate of #1028 (sorry, didn’t see).
Microseconds passed as MongoDate, DateTime, float or DateTime string (`'2000-01-01 00:00:00.123'`) are all handled.
> Added support for dates with milliseconds

- lib/Doctrine/ODM/MongoDB/Configuration.php
- lib/Doctrine/ODM/MongoDB/DocumentManager.php
- lib/Doctrine/ODM/MongoDB/MongoDBException.php
- lib/Doctrine/ODM/MongoDB/Repository/DefaultRepositoryFactory.php
- lib/Doctrine/ODM/MongoDB/Repository/RepositoryFactory.php
Added RepositoryFactory in the same way as in ORM and PHPCR. It will give the ability to inject additional services or parameters into Repository.
> Added RepositoryFactory [#891]

- lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php
Parsing file paths in Yaml is deprecated
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Yaml/Yaml.php#L58
> pass file content instead of file path to Yaml parser

- doctrine-mongo-mapping.xsd
The ```discriminatorField``` and ```discriminatorType``` mappings are missing from the XSD for the ```reference-one``` and ```embed-one``` type, they are only present for the respective *many mappings.
This PR adds them to the schema file.
> Add missing discriminator mapping to XSD

- lib/Doctrine/ODM/MongoDB/Cursor.php
- lib/Doctrine/ODM/MongoDB/EagerCursor.php
- lib/Doctrine/ODM/MongoDB/Query/Query.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH520Test.php
This PR moves reference priming from the ```Query::execute``` method to the cursor which iterates over the results (as described in #1065). This increases performance when iterating over part of a large query result (e.g. by setting ```skip``` and ```limit``` on the returned cursor before iterating) as it will not prime references for the entire result set.
Note that using ```prime``` for ```findAndUpdate``` and ```findAndRemove``` will prime references when executing the query since it will not return a cursor.
This also fixes a side effect of #520 where using ```getSingleResult()``` on a query without ```limit``` in combination with ```prime``` would prime references for all documents returned in the query instead of just the one returned by ```getSingleResult()```.
Feedback is greatly …
> Move reference priming to Cursor

- lib/Doctrine/ODM/MongoDB/Configuration.php
The namespace for the ```RepositoryFactory``` class has not been imported - this causes fatal errors when working with Reflection on the class
> Add missing namespace import

- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
In case a collection is marked as capped the related properties ```collectionCapped```, ```collectionSize``` and ```collectionMax``` are not serialized what results in wrong collection creations if the metadata has already been cached.
> Add missing serialization of MetadataClass properties

- docs/en/reference/basic-mapping.rst
As seen here, the type should be `raw`: https://github.com/doctrine/mongodb-odm/blob/94bc60445c95f627228fa7e72cc9958f70c033eb/lib/Doctrine/ODM/MongoDB/Types/Type.php#L57
> [docs] Fix 'raw_type' to 'raw'.

- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/DropCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php
This adds a proper return code in case a schema command throws an error. Without this, automated scripts (e.g. capifony) can't detect the error and act accordingly.
> Add proper return code to indicate errors in schema console commands

- .travis.yml
Travis matrix is quite big, as discussed with @jmikola this configuration will be enough for ODM
> [Travis] PHP 5.3 run all, 5.4 to 5.6 only stable driver

- docs/en/reference/events.rst
Because we know that `m` means month and not minutes.
> Fixed events.rst Lifecycle Callbacks example

- docs/en/reference/annotations-reference.rst
- docs/en/reference/collection-strategies.rst
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
- lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
- lib/Doctrine/ODM/MongoDB/PersistentCollection.php
- lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataInfoTest.php
- tests/Documents/Phonebook.php
This is an early implementation of how ``atomicSet`` and ``atomicSetArray`` could work in my opinion. There are some things that needs to be done
cc @jwage @jmikola @alcaeus @lavoiesl @blockjon
If this PR will reach its final form it will resolve #1009, #437, #1095 and #1094
> Adding atomicSet and atomicSetArray collection strategies

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1113Test.php
- tests/Doctrine/ODM/MongoDB/Tests/QueryLogger.php
Incorporates tests from PR #1113 (issue #1114) and query logging added in @malarzm's own branch.
> Ensure atomic collection updates use only one query

- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH909Test.php
@malarzm: I noticed that #909 had been fixed by some recent commits, but thought it be good to include the original test case.
> Regression test for cascade persist of associations

- lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1153Test.php
Fixes #1153 
For the record this PR can be considered as a hotfix for functionality that I've accidentally broken fixing #1141. I start to dislike the way we're managing atomic collection updates but I'm planning to fix it along with commit() flow I've described in https://github.com/doctrine/mongodb-odm/pull/1128#issuecomment-111864297 so I'm willing to merge this now and rewrite later.
> Fix updating of embedded documents if their atomic collection is not dirty

- lib/Doctrine/ODM/MongoDB/Cursor.php
- lib/Doctrine/ODM/MongoDB/EagerCursor.php
- lib/Doctrine/ODM/MongoDB/Query/Builder.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH520Test.php
This PR fixes a potential performance issue introduced with #1068. When using reference primers with non-eager cursors, the query would be executed multiple times, sometimes producing inconsistent results.
Using reference priming now implies using an eager cursor. Using eagerCursor = false and reference primers will result in an error.
Unfortunately, this re-introduces an issue described in #520, where calling ```getSingleResult()``` on a cursor with reference primers will always prime the entire result set.
> Prime references only from eagerCursor

- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractField.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH453Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/yaml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.yml
- tests/Documents/Article.php
- tests/Documents/Strategy.php
Fixes #1174. This commit finishes removing "unused" strategy from `collection` field. People who are still using `strategy` combined with `collection` and annotation mapping will now start getting error because `AbstractField` no longer has that property (which was the reason why our tests were green but YML/XML mappings suffered as reported in #1174)
@redthor could you maybe run your test suite against this PR?
> Straighten removing strategy from collection field

- lib/Doctrine/ODM/MongoDB/Query/Builder.php
- tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
For now we're manually adding discriminator field in select() but it would be nice if ODM could do that for us. Originally we were hit by this because we were searching by parent class which is abstract and instance of it could not be created.
Closes #879
> Wrong class is returned when using select() and single collection inheritance

- lib/Doctrine/ODM/MongoDB/Tools/DocumentRepositoryGenerator.php
- tests/Doctrine/ODM/MongoDB/Tests/Tools/DocumentRepositoryGeneratorTest.php
In order to make possible a clean fix in the DoctrineMongoDBBundle project I have added an extra parameter to the DocumentRepositoryGenerator->writeDocumentRepositoryClass method.
This extra parameter allows to generate classes in directories that doesn't directly map the namespace structure.
> Make easier PSR-4 compliance

- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Id.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
- lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/EmbeddedIdTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/IdTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH529Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH816Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH852Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataInfoTest.php
- tests/Documents/CmsPhonenumber.php
Fixes #857 (and by the way fixes #1178), closes #1183 and closes #819.
> Introduce sanity checks for IDs and fix overriding its type

- lib/Doctrine/ODM/MongoDB/Query/Builder.php
- lib/Doctrine/ODM/MongoDB/Query/Query.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
* Moves "priming implies eager cursor" logic to Query constructor, which is more reliable.
* Removes unnecessary exception when disabling a primer via `Builder::prime()` and then disabling eager cursors.
> Query and Builder priming improvements

- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/DoctrineAnnotations.php
> Don't import annotations whose names are reserved words in PHP7+

- docs/en/reference/annotations-reference.rst
- docs/en/reference/collection-strategies.rst
As discussed in #1192, this adds some more documentation to encourage users to employ atomic strategies when using versioned documents.
> Encourage use of atomic strategies with versioned documents

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
This fixes an issue where calling ```recomputeSingleDocumentChangeSet``` with an uninitialized proxy object would generate a changeset that rewrites the entire document.
> Don't compute changesets for uninitialized proxies

- lib/Doctrine/ODM/MongoDB/Cursor.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/CursorTest.php
This fixes a regression introduced in e2f23bc3eea11393995f0a799a02f34380201606 that causes wrong counts to be returned.
The default behavior for count() in a cursor is to return all elements, disregarding any skip/limit set.
> Fix regression with cursor counts

- lib/Doctrine/ODM/MongoDB/Cursor.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/CursorTest.php
This PR fixes issue
Given priming is enabled in query
And query result is empty
When _Cursor::getSingleResult()_ method is called
Then php error is triggered:
```
ReflectionProperty::getValue() expects parameter 1 to be object, null given
../mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php:1535
../mongodb-odm/lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php:140
../mongodb-odm/lib/Doctrine/ODM/MongoDB/Cursor.php:716
../mongodb-odm/lib/Doctrine/ODM/MongoDB/Cursor.php:347
../mongodb-odm/tests/Doctrine/ODM/MongoDB/Tests/Functional/CursorTest.php:126
```
> Do not prime references for single result when document is empty

- docs/en/reference/filters.rst
- lib/Doctrine/ODM/MongoDB/Query/Filter/BsonFilter.php
- lib/Doctrine/ODM/MongoDB/Query/FilterCollection.php
- tests/Doctrine/ODM/MongoDB/Tests/Query/Filter/BsonFilterTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Query/Filter/Filter.php
When BsonFilter class gets to mock, it shows case sensitive problem. If any class inherits from it, the problem does not exists - the inherited class can change typed argument (ClassMetaData to ClassMetadata). The only way I know how to test it,  is to creating a mock.
> Fixing ClassMetadata to work on case sensitive filesystems

- lib/Doctrine/ODM/MongoDB/PersistentCollection.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1232Test.php
Fixes #1232.
When removing a document that contains a PersistentCollection, we clear the snapshot of the collection and reset the isDirty flag. This invoked the ```count()``` method on the collection itself which in turn could cause errors when using ```references``` in a ```repositoryMethod``` for a different PersistentCollection.
> Fix counting when clearing snapshot in PersistentCollection

- docs/en/reference/architecture.rst
- Replaces "ORM" by "ODM"
- Also removes the "2" from "Doctrine 2" because Doctrine Mongo ODM is currently in 1.X
PS: Github added EOL EOF automatically.
> [Docs] Fix wrong text about DocumentManager

- lib/Doctrine/ODM/MongoDB/PersistentCollection.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/OrphanRemovalTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1225Test.php
This fixes a minor issue where removing an element from a PersistentCollection with orphanRemoval enabled and then re-adding it to the same collection leaves it scheduled for removal. This can produce invalid references.
This PR also fixes an issue where using ```set()``` in a PersistentCollection with orphanRemoval enabled would not remove an element that was overwritten and is no longer part of the collection.
> Unschedule orphan removal if an element is re-added

- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferenceRepositoryMethodTest.php
- tests/Documents/BlogPost.php
Lately I omitted on purpose `mappedBy` on `ReferenceMany` using `repositoryMethod` since there was no owning side and using `count()` on such uninitialized `PersistentCollection` was stubbornly returning `0`.
> Using repositoryMethod should imply inverseSide

- lib/Doctrine/ODM/MongoDB/PersistentCollection.php
Fixes #1255.
This fixes an issue where adding null to a PersistentCollection (or overwriting an element with null) would try to unschedule orphanRemoval for that object.
> Don't unschedule orphanRemoval for null

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
This PR fixes some issues with documents using the NOTIFY change tracking policy, namely:
* Committing a document of this kind multiple times raised an `Undefined index` notice as reported in #740. Fixed the error and created a test case for it.
* Committing only a single document made the UnitOfWork lose changes of all other managed documents with NOTIFY change tracking policy. Fixed this too and also created a test case for it.
* Additionally I found that the current test case for the this change tracking policy (namely: `UnitOfWorkTest::testChangeTrackingNotify`) used a document without the required `@ODM\ChangeTrackingPolicy("NOTIFY")` annotation as its test subject, so the test didn't test what it supposed to test. I added the missing annotation to this dummy document.
> NOTIFY change tracking policy fixes

- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateDocumentsCommand.php
add no-backup option. default is false. if you want to have backups, need to specify --generate-backup=true on command line.
For future consideration: Update documentation to specific that options where false is an option must be specified as <option>=0, since false is recognized as a string and thus resolves to TRUE in php.
Thanks!
> No backup option

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/EmbeddedTest.php
Follow up of #1252 which also takes care of fixing reused embedded documents (and collections) as soon as document is persisted. As a side effect (heh) parent association is now available just after the persist (which is neat since it'll be available in `prePersist` event - now I wonder if tests for this should be added).
Also closes #509 as we won't get any nearer behaviour that was wanted there.
> Set parentAssociation on persist and fix embeds by then

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/EmbeddedTest.php
This is a bug that happens when the name annotation of an embed document is different of the field name itself.
Related: https://github.com/doctrine/mongodb-odm/commit/85d91b74b64057d9f812d030d6d15d51e9fa278d
> Use fieldName in mapping instead of name when persisting

- lib/Doctrine/ODM/MongoDB/PersistentCollection.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1275Test.php
- tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
Supersedes #1278 and personally I like this one better. Also I was thinking if it's worth removing embedded documents out of orphan removal's interest but probably that would mean duplicating logic for cascading.
> Moved logic for scheduling orphanRemoval

- docs/en/reference/events.rst
- lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Events/LifecycleCallbacksTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM43Test.php
Closes #902 
This PR contains a tiny BC break - before `preLoad` lifecycle callback received `$data` by reference directly, now it receives a `PreLoadEventArgs` as it should BUT I wouldn't count it as BC break though - that event wasn't even documented.
> Lifecycle callbacks should receive event arguments

- docs/en/reference/basic-mapping.rst
Fixes #1295.
This updates the example for the NONE ID generation strategy to define a type in the mapping and avoid casting the string identifer to MongoId.
> Update documentation for NONE strategy

- lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
- lib/Doctrine/ODM/MongoDB/Query/Expr.php
- tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
Before it was throwing an exception that field was not found. Test case is written like this only for the sake of testing, normally we use same type of references everywhere, only fields are named differently in child classes for the sake of making sense :)
> Expr::references should go through discriminator map

- docs/en/reference/indexes.rst
- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractIndex.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/AbstractDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/XmlDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/InvalidPartialFilterDocument.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/PartialFilterDocument.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.InvalidPartialFilterDocument.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.PartialFilterDocument.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/yaml/TestDocuments.PartialFilterDocument.dcm.yml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/yaml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.yml
- tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
MongoDB 3.2 adds support for [partial indexes](https://docs.mongodb.org/manual/core/index-partial/). This PR adds support for adding partialIndexExpression options to the index specification.
Examples:
- YAML:
```
indexes:
index1:
keys:
username: desc
options:
unique: true
dropDups: false
partialFilterExpression:
version: { $gt: 1 }
discr: { $eq: 'default' }
```
- XML:
```
<indexes>
<index unique="true">
<key name="username" order="desc" />
<option name="dropDups" value="false" />
<partialFilterExpression>
<field name="version" value="1" operator="gt" />
<field name="discr" operator="eq" value="default" />
</partialFilterExpression>
</index>
</indexes>
```
- Annotations:
```
/**
* @ODM\Indexes(
*     @ODM\Index(keys={"username"="asc"},dropDups=true,partialFilterExpression={"counter"={"$gt" …
```
> Add support for partial indexes

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Events/PreUpdateEventArgsTest.php
As of this PR the collection will be included in changeset if at least one of following is true
1. at least one element was added
2. at least one element was removed
3. collection was cleared
Collection won't be in changeset if only one of its element was modified.
Thoughts? :)
> Include Embed/RefMany in changeset

- composer.json
While ODM does not officially support PHP 7 (due to the legacy MongoDB driver not being available), there are alternatives the people may use. This PR aims to allow those developers to use ODM with a polyfill for ext-mongo (e.g. mongofill, mongo-php-adapter) in PHP 7.
> Allow PHP 7 in composer.json

- docs/en/reference/events.rst
- lib/Doctrine/ODM/MongoDB/Event/DocumentNotFoundEventArgs.php
- lib/Doctrine/ODM/MongoDB/Events.php
- lib/Doctrine/ODM/MongoDB/Proxy/ProxyFactory.php
- lib/Doctrine/ODM/MongoDB/Utility/LifecycleEventManager.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencesTest.php
Supersedes #532, Closes #1258.
This builds on top of the code added in #532. The new `DocumentNotFoundEventArgs` class contains the proxy object and its identifier. Event subscribers can choose to handle the missing document and call `disableException()` on the $eventArgs object to prevent the `DocumentNotFound` exception from being thrown.
As mentioned in the ticket, this event is not available as a lifecycle callback because we don't have a valid object on which to call a lifecycle callback.
> Dispatch an event when proxy initialization fails

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH971Test.php
This PR doesn't bring full PHP 7 compatibility but it removes a couple of issues that will arise should one manage to get ODM running on PHP 7:
- As mentioned in the [PHP 7 Upgrade log](https://secure.php.net/manual/de/migration70.incompatible.php), changes to variable handling cause an array to string conversion in DocumentPersister
- There were a couple of deprecated annotations still being used in tests. Due to string and integer being reserved keywords in PHP 7, these annotations are not loaded and cause errors.
> Fix PHP 7 compatibility errors

- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataInfoTest.php
This fixes a regression introduced in #1352 where using the now deprecated `Increment` type would cause a `MappingException`.
> Fix regression with increment strategy

- lib/Doctrine/ODM/MongoDB/DocumentManager.php
- lib/Doctrine/ODM/MongoDB/Id/AlnumGenerator.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
- lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
- lib/Doctrine/ODM/MongoDB/MongoDBException.php
- lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Query/Builder.php
- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/ClearCache/MetadataCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/DropCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/DisconnectedClassMetadataFactory.php
- lib/Doctrine/ODM/MongoDB/Tools/DocumentGenerator.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
Threw in ternary shorthand as a bonus. This feature was introduced in PHP 5.3 so no reason not to use it.
> Removed redundant parens and incorrect double-quote usage.

- lib/Doctrine/ODM/MongoDB/Cursor.php
- lib/Doctrine/ODM/MongoDB/Query/Builder.php
In the same vein as doctrine/mongodb#251.
> Corrected fluent interface docblock annotations.

- lib/Doctrine/ODM/MongoDB/Types/DateType.php
- tests/Doctrine/ODM/MongoDB/Tests/Types/DateTypeTest.php
Dates with microsecond values less than 100000 are not correctly converted to PHP objects.
When converting from MongoDate objects, the `usec` field returns an integer that is concatenated directly to a string formated date in `craftDateTime`. For example, the value 1.0001 gets split into 1 second and 100 microseconds, which then gets concatenated as "1.100".
When converting numeric values, the sub-seconds are broken into a string which is then padded to six values; however, it is casted to an int first. For example, 1.0001 gets split into a string "0001" which is cast to the integer 1 and padded to "100000", resulting in "1.100000".
In order to properly convert microseconds, they are string padded without converting to an integer.
> Fix broken conversion of microseconds less than 100000.

- composer.json
This removes the need for the extra driver requirement in composer.json and brings driver and PHP versions for both packages to the same requirement.
> Require latest stable version of doctrine/mongodb

- tests/Documents/Functional/SimpleEmbedAndReference.php
A test document class ``SimpleEmbedAndReference`` contained ``targetDocument`` settings that did not match property and annotations, this PR fixes them. The only test method that actually uses the document is ``FunctionalTest::testSimplerEmbedAndReference`` that only checks the association type, not actually whether it's embedded or referenced.
> Fixed targetDocument types to match property names and annotations

- .travis.yml
While composer.json has allowed installing on PHP 7 for a while (given that the `ext-mongo` requirement is fulfilled), there were no tests for that platform. This PR adds alcaeus/mongo-php-adapter as polyfill to the PHP 7 version of the build matrix.
Note: due to a [bug with composer](https://github.com/composer/composer/issues/5030) the build step installing the polyfill is running with the `ignore-platform-reqs` flag. Once this bug is fixed the flag should be removed.
> Add PHP 7 to the build matrix using polyfill

- lib/Doctrine/ODM/MongoDB/Query/Expr.php
- tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
Bug discovered in #1349 and planned to be solved in #1405, but created this fix for the 1.0.x branch first.
> Fix the ' needs an Object' exception for simple references

- docs/en/reference/query-builder-api.rst
- lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Query/Builder.php
- lib/Doctrine/ODM/MongoDB/Query/Query.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/HydratorTest.php
- tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
This not only fixes #1377 but also exposes `readOnly` as an option for query builder. 
Read-only takes precedence over `refresh` when combined. Document fetched in read-only manner can be `merge`d back into `DocumentManager` at developer's discretion, forbiding such action is out of scope of this PR (IMHO :)
> Add option to fetch documents as Read-Only

- lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
- tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
This builds up on @notrix PR #1390 and changes way `typeClass` is obtained to prevent duplicating code
> Fix for fatal exception if persisted collection was unserialized

- lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
This PR backports patch from #1414 into `1.0.x` branch. Tests are not carried over because they're built on stuff that is not available in `1.0.x` branch, they will be merged with original PR into `dev-master`
> Fix bug when priming references nested in embedded documents

- lib/Doctrine/ODM/MongoDB/PersistentCollection.php
- tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
This is a backport of #1411 into the 1.0.x branch. The changes for 1.1 affect PersistentCollectionTrait but the functionality is already present in 1.0.x in PersistentCollection.
> Fix exception if PersistentCollection was unserialized

- docs/en/reference/annotations-reference.rst
- docs/en/reference/working-with-objects.rst
- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Configuration.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Document.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/AnnotationDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/yaml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.yml
This PR aims to fix #1409. Please let me know if there is something missing that I can improve or there should be more tests.
I had to move the default options from the `UnitOfWork` to the `DocumentPersister` to ensure it can be determined if the given options are passed through `flush()` or are the system wide defaults.
> Write concern per document

- docs/en/reference/query-builder-api.rst
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1418Test.php
This builds on top of the tests written in #1418.
When merging previously unmanaged documents, we need to initialize `PersistentCollection` instances if the association is configured to cascade merges. This way, ODM picks up embedded documents that were not previously stored. This can happen when using hydrators with a read-only hint to hydrate data from an external source and then using `merge` to manage the document for a later write to the database.
> Fix merging read-only documents with persistent collections

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/SplObjectHashCollisionsTest.php
This is a backport of #1430 into the 1.0.x branch to fix potential object hash collision with embedded documents.
Supersedes #1430 and #1023.
> Prevent spl_object_hash collisions

- docs/en/reference/best-practices.rst
PHP 7 is not fully unicode-aware yet.
Like Doctrine ORM's docs( http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/best-practices.html#don-t-use-special-characters ),
we should remove a part of "(PHP 7)" .
> Fix best-practices.rst

- lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php
Presently, if a Yaml mapping file has a parse error, it can be tough to track down as the resulting error message only tells you the line of the error and not the filename.
This PR adds a better exception error message that appends the filepath to the end of the parse exception.
The current PR catches only "\Symfony\Component\Yaml\Exception\ParseException" and perhaps it would be better to catch all exceptions, but then I don't know which exception class to "re-throw". Thoughts?
> Improved Yaml ParseException exception message

- lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1435/Doctrine.ODM.MongoDB.Tests.GH1435Document.dcm.yml
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1435/Doctrine.ODM.MongoDB.Tests.GH1435DocumentIncrement.dcm.yml
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1435Test.php
Fixes #1435.
This also uncovered a bug where using the increment strategy for ID generation could lead to errors when upserting documents due to a name conflict with strategies.
> Fix upserts for documents with YAML mapping

- docs/en/index.rst
[doctrine-odm](http://stackoverflow.com/questions/tagged/doctrine-odm) while a bit more broad at a glance is more alive than currently linked [doctrine-mongodb](http://stackoverflow.com/questions/tagged/doctrine-mongodb) and contains a lot of `mongodb` related questions. Also I follow the first one and try to answer question over there while about the current tag I have learnt only recently ;)
> Change StackOverflow tag

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/CollectionsTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/EmbeddedTest.php
- tests/Documents/Bars/Bar.php
Found this bug while working on new change sets; in https://github.com/doctrine/mongodb-odm/pull/1339 I was so happy that collections are in the change set that I haven't checked what was in the change set :) By the way fixed the same thing for when embedded document is exchanged.
> Fix changeset missing old value for exchanged associations

- lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
- tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
Fixes #1455 and additionally ensures `isEmpty` method is forwarded when collection is initialized.
> Use decorated methods instead of general ones

- tests/Doctrine/ODM/MongoDB/Tests/DocumentManagerTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataFactoryTest.php
- tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Query/ExprTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Query/Filter/BsonFilterTest.php
- tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
- tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
as `getMock` was deprecated. As a bonus I changed now unnecessary long `getMockBuilder` to `createMock` too
> Use createMock where possible

- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1468Test.php
- tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
This PR aims to ensure also a GridFS collection is dropped when calling `$dm->getSchemaManager()->dropCollections();`. Currently dropping a GridFS collection has no affect and the data remains in there.
> Ensure GridFS collections are dropped properly

- docs/en/reference/best-practices.rst
- docs/en/reference/working-with-objects.rst
Removed a couple of paragraphs from the docs. Serializing private properties from proxy object seems to no longer be a problem, see the following 3v4l snippet: https://3v4l.org/1Ufld
About public properties: while not recommended to be mapped, there is nothing there that wouldn't work. Public properties in proxy objects are unset and lazy loaded through the `__get` and `__set` magic accessors, properly triggering proxy initialization whenever accessed. Thus, I also removed that section from the documentation as it's not correct.
> Update mapping documentation

- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/DiscriminatorField.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DiscriminatorsDefaultValueTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferenceDiscriminatorsTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH267Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH389Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH788Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH942Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH971Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM50Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
- tests/Documents/Functional/SameCollection1.php
- tests/Documents/Functional/SameCollection2.php
- tests/Documents/Project.php
- tests/Documents/Server.php
- tests/Documents/UserUpsert.php
- tests/Documents/UserUpsertIdStrategyNone.php
Advocated usage is now `@ODM\DiscriminatorField("foo")`
> [1.2] Deprecate DiscriminatorField's properties

- docs/en/reference/annotations-reference.rst
- docs/en/reference/indexes.rst
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Document.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
- lib/Doctrine/ODM/MongoDB/MongoDBException.php
- lib/Doctrine/ODM/MongoDB/Query/Builder.php
- lib/Doctrine/ODM/MongoDB/Query/FieldExtractor.php
- lib/Doctrine/ODM/MongoDB/Query/Query.php
As promised, follow up to #1476. Right now the feature is more broken than working thus giving developer false sense of security. To name few things that are wrong:
1. [Compound index order is not respected](https://github.com/doctrine/mongodb-odm/issues/761)
2. [Index intersection](https://docs.mongodb.com/manual/core/index-intersection/) added in Mongo 2.6 is not considered
3. [`$or` clauses can use own indexes](https://docs.mongodb.com/manual/reference/operator/query/or/#or-clauses-and-indexes) and that's not considered
I even took a stab at some of things listed above in #812 - it reached +1.2k and still was wrong. In my opinion all this adds unnecessary complexity and things to maintain, especially if Mongo would again introduce some new index-related feature making simple true/false …
> [1.2] Deprecate requireIndexes and stuff thereto related

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/DocumentRepositoryTest.php
This PR fixes an issue introduced with #1363 when running queries like `$dm->getRepository(User::class)->findOneBy(['account' => $account]);`, with `$account` being a referenced document. When using the `references` method of the query builder, the query array looks like this:
```
[
'account.$id' => MongoId(...)
]
```
When using `includesReferenceTo` which is made for `@ReferenceMany` mappings, the result looks like this:
```
[
'account' => [
'$elemMatch' => [
'$id' => MongoId(...)
]
]
]
```
However, the implementation in the DocumentPersister always yielded a full DBRef object:
```
[
'account' => [
'$ref' => 'accounts',
'$id' => MongoId(...)
'$db' => 'mydatabasename'
]
]
```
This caused issues when forcing queries to be covered by indexes (through the `notablescan` option in MongoDB), …
> Fix query preparation when querying for referenced object

- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/DiscriminatorField.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
PR deprecating `name` and fixing our test suite will be sent soon (travis will be green again after #1479 is merged and this rebased)
> [2.0] Remove DiscriminatorField's name and fieldName

- docs/en/reference/find-and-update.rst
Fixed example for clarity. `->field('in_progress')->set(true)` is actually part of the update, not the find.
> Fixed find-and-update.rst example

- lib/Doctrine/ODM/MongoDB/DocumentManager.php
- tests/Doctrine/ODM/MongoDB/Tests/DocumentManagerTest.php
Fixes #1394. This allows using falsey values as identifiers with references. All other checks to identifiers I could find explicitely check for null values, so it makes sense to do the same in createDbRef.
> Allow creating references to "empty" identifiers

- composer.json
We're using `createMock` which was introduced in `5.4` (and sometimes it's not picked automatically https://github.com/doctrine/mongodb-odm/pull/1463#issuecomment-240723486)
> Bump PHPUnit requirement

- .travis.yml
- tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php
We need MongoDB 3.2 to test the upcoming `$lookup` stages in the aggregation builder. For better compatibility we also test against MongoDB 2.6 which is the lowest version required for most aggregation queries.
> Test against MongoDB 3.2 and 2.6

- docs/en/reference/basic-mapping.rst
Docs were using an old class name. With these changes, was able to follow documentation and create an custom mapping type.
> Correct Class Name in Custom Mapping Type Docs

- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Bin.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/BinCustom.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/BinFunc.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/BinMD5.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/BinUUID.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/BinUUIDRFC4122.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Bool.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Boolean.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Collection.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Date.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Float.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Hash.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Int.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Integer.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Key.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/ObjectId.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Raw.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/String.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Timestamp.php
Following discussion from https://github.com/doctrine/mongodb-odm/issues/1459#issuecomment-255722659
Instead of just saying that this class is deprecated (and probably got a lot of issues related to that) add an alternative to it.
> Add alternative to deprecated annotations

- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
By using the already existing `createCollection` instead of doing a fake command it's possbile to avoid calls to MongoDBs deprecated `eval`.
When using the `schema:create`-command at deploy time this will avoid MongoDB startup warnings like
```
"2016-10-21T14:05:35.870+0000 W COMMAND  [conn581654] the eval command is deprecated"
```
> Avoid call to MongoDBs deprecated eval

- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
This PR removes the version check in SchemaManager introduced with #1521. This is necessary since the `serverStatus` command requires extra privileges which may or may not have been given to the user being used. Instead, users should skip the creation of the database by passing the `--collection` and `--index` options, omitting the `--db` option when creating the schema using the `schema:create` command.
The deprecation of the `createDatabases` and `createDocumentDatabase` methods in `SchemaManager` stays intact; the methods will be removed with ODM 2.0.
> Remove version check in SchemaManager

- composer.json
It is already suggested by doctrine/mongodb which is required by this
library.
> Remove suggest mongo-php-adapter

- .travis.yml
- tests/Doctrine/ODM/MongoDB/Tests/Persisters/DocumentPersisterGetShardKeyQueryTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Types/TypeTest.php
With the old matrix, we'd have 10 builds, which seems excessive. Since there's no need to test every PHP version against every MongoDB version, we only test PHP 5.6 against each MongoDB version.
Note: tests against MongoDB 3.4 are not possible at this time; I'll add them once MongoDB 3.4 is available on the repository we're using in our travis builds.
> Add PHP 7.1 and MongoDB 3.2 to the build matrix

- tests/Doctrine/ODM/MongoDB/Tests/Types/TypeTest.php
The test in question would fail on PHP 7.1 when run at a time where the millisecond portion of a date was < 100 due to incorrect handling of the microsecond string.
> Correctly format microseconds in test

- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/ValidateCommand.php
Implements #1271. This one is pretty straightforward and just lets developer knows that something is wrong, we may consider telling more.
> Add command to validate mapping

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/EmbeddedTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1525Test.php
Fixes #1525.
The problem is that the changeset wrote down the old embedded document, which was then used when trying to persist changes. I don't like adding another check for the embedded document parent, maybe @malarzm has a better idea?
> Fix embedded document parent before computing changeset

- .travis.yml
- tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Persisters/DocumentPersisterGetShardKeyQueryTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Types/TypeTest.php
This is a backport of #1530 to the 1.1.x branch to ensure PHP 7.1 compatibility of the currently supported release line.
> Test against PHP 7.1 (1.1.x)

- .travis.yml
- tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
This adds MongoDB 3.4 to the test suite and switches to the `mongodb-org` package instead of `mongodb-enterprise`. Since `mongodb-org` 2.6 is not available, we drop it from the build matrix to avoid having two different apt repositories in the build.
> Test against MongoDB 3.4 (1.1.x)

- .travis.yml
- docs/en/reference/aggregation-builder.rst
- tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/LookupTest.php
- tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
This brings in the commits from #1540 and #1544, including a fix for `$lookup` stages on MongoDB 3.4.
> Test against MongoDB 3.4 (master)

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1525Test.php
I'll comment on changes separately but as for now failing test case @redthor has provided in #1525 is fixed
> Fix more re-used embedded docs issues

- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
Fixes #1271.
The previous solution would always require specifying an inheritance type, which makes sense for documents but seems weird for embedded documents. With this PR, this changes to serialize the inheritance information (inheritance type and discriminator data) if an inheritance type was specified or if the discriminator field was given. This should fix hard to find cases where data can't be stored or loaded once the metadata was loaded from cache.
> Change serialization of inheritance fields

- lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1572Test.php
Fixes an issue where having an inverse reference with a limit set would return the wrong number of elements when the collection isn't initialized.
> Fix counting of inverse collections with limit

- docs/en/reference/annotations-reference.rst
- docs/en/reference/priming-references.rst
- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/ReferenceMany.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php
- lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/AbstractDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/PrimedCollectionDocument.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.PrimedCollectionDocument.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/yaml/TestDocuments.PrimedCollectionDocument.dcm.yml
- tests/Documents/BlogPost.php
- tests/Documents/Comment.php
This PR adds support for reference priming in inverse collections. This avoids having to declare a `repositoryMethod` just to use primers, e.g.:
```php
// Document
/**
* @ODM\ReferenceMany(
*     targetDocument=User\Follow::class,
*     repositoryMethod="getFollowers",
*     sort={"createdAt"="desc"},
*     cascade={"remove"},
* )
*/
protected $followers;
// Repository
public function getFollowers(User $user)
{
return $this->createQueryBuilder()
->field('followed')
->equals($user)
->field('follower')
->prime()
->getQuery()
->getIterator();
}
```
This can now be shortened using the new `primers` property:
```php
/**
* @ODM\ReferenceMany(
*     targetDocument=User\Follow::class,
*     mappedBy="followed",
*     primers={"follower"=true}
*     sort={"createdAt"="desc"},
* …
```
> Support priming references in inverse many relationships

- docs/en/reference/introduction.rst
In the result of the example the `$project` is assigned to the `$manager`, but this method is missing from the initial instructions
> [DOCS] Missing instruction in example

- lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/VersionTest.php
I have a versioned document, with a version field, using a custom name.
"version" is the field name I use in the PHP object and "_version" is the name I use in the underlying document.
I have added an embedMany field and can no longer update my document.
A Doctrine\ODM\MongoDB\LockException is thrown.
It seems that the problem comes from the CollectionPersister, that adds the version field name to the query, when it should instead use the related field mapping name.
> Doctrine\ODM\MongoDB\LockException when using versioning, a custom name for the version field and embedMany

- docs/en/index.rst
- docs/en/reference/transactions-and-concurrency.rst
I was looking for the ODM equivalent of http://doctrine-orm.readthedocs.org/en/latest/reference/transactions-and-concurrency.html, but could not find one.
Basically I took the ORM documentation on the subject which I adapted to the ODM, according to both the official MongoDB documentation and my own experience working with Mongo and the ODM.
> Transactions and concurrency documentation

- lib/Doctrine/ODM/MongoDB/Repository/DefaultRepositoryFactory.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH267Test.php
- tests/Doctrine/ODM/MongoDB/Tests/RepositoryFactoryTest.php
Lately I realized that our implementation is a bit off compared to ORM's one so here are 2 bug-fixes (since they're touching the same class and even in same place I packed both into same PR). Once we merge this I'd add `AbstractRepositoryFactory` as writing own one is quite tedious (copy default one and add your instantiation logic, I think we could add something like [AbstractPersistentCollectionFactory](https://github.com/doctrine/mongodb-odm/blob/b5d0c89cd63b3e05f58071c1025f7b776fcaa157/lib/Doctrine/ODM/MongoDB/PersistentCollection/AbstractPersistentCollectionFactory.php))
> Update default repository factory

- docs/en/reference/aggregation-builder.rst
- docs/en/reference/query-builder-api.rst
- lib/Doctrine/ODM/MongoDB/Query/Builder.php
The `group` command [was deprecated in MongoDB 3.4](https://docs.mongodb.com/v3.4/reference/method/db.collection.group/)
> Deprecate Query Builder's group

- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/DoctrineAnnotations.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
I wonder if I should add trigger in `DoctrineAnnotations.php` in case somebody required that file on one's own...
> Deprecate AnnotationDriver::registerAnnotationClasses

- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
Fixes #1627.
Not sure about tests here, but it fixes the issue.
> Don't generate proxy classes for embedded documents

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
A document's local version should only be incremented when the database version is, otherwise, if the lock exception is caught, a second persist & can succeed and overwrite data.
> Lock exception leaves document with bad revision

- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
Follows up on #1628 and adds query result documents to the proxy generation exclusion list.
> Don't generate proxies for query result documents

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
Backport of #1592 for 1.1. This was also merged to master.
> Fix document local revision incrementing even when mongo update fails

- lib/Doctrine/ODM/MongoDB/DocumentManager.php
Hi,
`DocumentManager::getHydratorFactory()` return type is wrong, see https://github.com/doctrine/mongodb-odm/blob/f7379e4eeaffcd33d83fb4b0fcc4ccce1acb8a4e/lib/Doctrine/ODM/MongoDB/DocumentManager.php#L84
> Fix DocumentManager::getHydratorFactory() return type

- .travis.yml
- tests/Doctrine/ODM/MongoDB/Tests/Functional/BinDataTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/IdTest.php
This fixes failures when running the tests against the new 1.3.0 mongodb driver version.
> Fix invalid test data for UUID bin data

- docs/en/reference/annotations-reference.rst
- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Document.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/ReadOnlyDocumentTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/yaml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.yml
Closes #1602 (cc @tux-rampage)
Allowing document to be upserted opens a way to overwriting its value but otherwise it would be impossible to have read only document with user-generated identifier. We may want to revisit this once we have official `upsert` API :)
> Add read only documents

- composer.json
Fixes #1648. Allows installing doctrine/instantiator 1.1.x on machines with PHP 7.1.
> Relax version constraint for doctrine/instantiator

- composer.json
- tests/Doctrine/ODM/MongoDB/Tests/Functional/IdTest.php
As @jmikola mentioned in https://github.com/doctrine/mongodb-odm/pull/1646#discussion_r141097347, using base64 encoded data isn't necessary for binary data types. To avoid any confusion, we switch to using regular PHP strings.
This also fixes a small error in the composer version constraint for doctrine/instantiator. It didn't allow 1.0.0 before, it shouldn't allow it now.
> Update tests and wrong version constraint

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Mocks/ExceptionThrowingListenerMock.php
- tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
As indicated in #1051, calling `flush` in an event subscriber can have unwanted side effects and shouldn't be done. To prepare people for this change, ODM 1.2 will throw deprecation warnings to give users a chance to fix offending event subscribers before 2.0 starts throwing exceptions.
> Throw deprecation warning on nested flushes

- docs/en/reference/annotations-reference.rst
- docs/en/reference/reference-mapping.rst
- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Lookup.php
- lib/Doctrine/ODM/MongoDB/DocumentManager.php
- lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
- lib/Doctrine/ODM/MongoDB/Query/Expr.php
- lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/LookupTest.php
- tests/Doctrine/ODM/MongoDB/Tests/DocumentManagerTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Query/ExprTest.php
- tests/Documents/ReferenceUser.php
- tests/Documents/User.php
Supersedes #1566.
As discussed in our last hangout, this is what remains of the DBRef replacement. DBRef is not deprecated (yet), athough we might decide to deprecate it at this time. At this time the PR is feature complete, I'd like to write a whole bunch of tests to ensure the whole discriminator handling/omitting target collection name works as I'd expect it to.
The new reference object only stores an ID and optionally a discriminator field. The main difference to DBRef is that it can be used in aggregation pipeline stages that don't handle DBRef objects because of the `$` in field names (e.g. `$lookup` and `$graphLookup`).
I'll also revisit #1527 to see if we can store additional fields in the reference (which would also apply to DBRef objects).
> Add generic reference as replacement for DBRef

- .travis.yml
Fixes https://travis-ci.org/doctrine/mongodb-odm/jobs/287745628#L501
Also removes the tests against MongoDB 3.0 since travis-ci comes with 3.2 installed and we can't downgrade. It's not optimal, but I don't have a better solution at this time.
> Allow unauthenticated install of mongodb-org

- lib/Doctrine/ODM/MongoDB/Cursor.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
- lib/Doctrine/ODM/MongoDB/Query/Builder.php
Fixes an empty deprecation message due to `sprintf` being called with too few arguments.
Testing the new master branch, I found that we trigger too many deprecation notices when using the annotation driver. This pull request changes that behavior, now deprecation notices are only triggered if `slaveOkay` or `requireIndexes` are being turned on.
> Fix deprecation messages for slaveOkay

- lib/Doctrine/ODM/MongoDB/Id/IncrementGenerator.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/IdTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Id/IncrementGeneratorTest.php
Supersedes #1634 since maintainer contributions are disabled on the pull request.
Thanks for implementing this @stampycode, I'll merge it once the build is stable and include it in 1.2.0.
> Enable a custom starting id

- tests/Doctrine/ODM/MongoDB/Tests/Functional/FilesTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/FunctionalTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH816Test.php
- tests/Doctrine/ODM/MongoDB/Tests/HydratorTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/XmlDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Query/FilterCollectionTest.php
I've refactored some tests with [`assertFileExists`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFileExists), [`assertNull`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertNull), [`assertFalse`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFalse), [`assertTrue`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertTrue) and [`assertEmpty`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertEmpty) methods.
> Refactoring tests

- docs/en/reference/map-reduce.rst
There is a typo, if we want to map-reduce the event document based, we need to `createQueryBuilder` on top of the document `Documents\Event`
> Fixed typo in map-reduce doc

- doctrine-mongo-mapping.xsd
The XSD defines a default value (`string`) for the `type` attribute of the `field` tag. PhpStorm (or an extension?) even issues a warning ("Redundant default attribute value assignment") when I set the attribute to `string`.
So either the code has to be changed to reflect the XML definition, or the definition needs to be changed - which this PR does.
> Remove default value from type attribute

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Persisters/DocumentPersisterGetShardKeyQueryTest.php
From mongodb perspective it's all good to shard on refence id. So doctrine should know how to generate query for such sharded collections.
> Enable shard key to be a referenced object id

- .travis.yml
- docs/en/reference/introduction.rst
Using `ignore-platform-reqs` can cause a bunch of errors down the line (e.g. by installing incompatible package versions not suited for the current PHP version). Thus, `ext-mongodb` is provided via `config.platform`.
> Don't use ignore-platform-reqs when installing mongo-php-adapter

- .travis.yml
- docs/en/reference/introduction.rst
- docs/en/reference/storage-strategies.rst
- lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/FilesTest.php
MongoDB 3.6 removes the `$pushAll` operator, which has been deprecated since MongoDB 2.4. This pull request replaces `$pushAll` for `$push` with `$each`, as [recommended by MongoDB](https://docs.mongodb.com/manual/release-notes/3.6-compatibility/#pushall-compatibility).
> Remove usage of pushAll operator in CollectionPersister

- lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage/AbstractBucket.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage/GraphLookup.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage/ReplaceRoot.php
- lib/Doctrine/ODM/MongoDB/DocumentRepository.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Query/Query.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Iterator/CachingIteratorTest.php
I've removed the `else`s when we have already returned something :put_litter_in_its_place:
> Clean elses

- .travis.yml
- composer.json
This makes it easier to add code quality checks later on. Additionaly, xdebug is disabled for all builds but one that runs with coverage; that should hopefully make the test suite faster again.
Also, I've noticed that we still support PHP 7.0, so that's definitely going out the door. Might even drop 7.1 later on.
> Use build stages for travis-ci

- lib/Doctrine/ODM/MongoDB/DocumentManager.php
FWIW there are 2 usages of the removed method but they're both in code paths removed by #1720
> [2.0] Remove DocumentManager::createDbRef

- docs/en/conf.py
Follow up for https://github.com/doctrine/doctrine-sphinx-theme/pull/12 also needs to be backported to 1.2.x branch later.
> Add subproject to docs config

- tests/Doctrine/ODM/MongoDB/Tests/Functional/CollectionsTest.php
Previously, the capped collection document was never used. This also revises both tests to assign mapped fields on the documents for consistency.
Just fixing something I noticed while investigating https://github.com/doctrine/mongodb-odm/issues/1745.
> Fix normal/capped collection tests

- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
- tests/Documents/Sharded/ShardedByUser.php
This backports #1693 to the 1.2 branch. My initial hunch regarding field name translation was correct - this was an additional issue affecting all shard keys that have a different database name. This is also fixed in this PR.
// cc @notrix
> Schema manager should also know how to handle shard key on reference

- lib/Doctrine/ODM/MongoDB/DocumentManager.php
- lib/Doctrine/ODM/MongoDB/DocumentRepository.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/MongoDBException.php
- lib/Doctrine/ODM/MongoDB/PersistentCollection/DefaultPersistentCollectionGenerator.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateHydratorsCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GeneratePersistentCollectionsCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/QueryCommand.php
- phpcs.xml.dist
- tests/Documents/Ecommerce/ConfigurableProduct.php
- tests/bootstrap.php
- tools/sandbox/config.php
On this one:
- Remove alias functions, as well forbidden ones
- Remove assignments in `if` condition
> [CS] Start to fix excluded ones

- lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Operator.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataFactoryTest.php
```diff
-occurence
+occurrence
```
Also a test had `Seperator` instead os `Separator`
> Fix some misspellings

- lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
- lib/Doctrine/ODM/MongoDB/DocumentManager.php
- lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
- lib/Doctrine/ODM/MongoDB/MongoDBException.php
- lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Query/Expr.php
- phpcs.xml.dist
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataFactoryTest.php
> Stop ignoring DoubleQuoteUsage.ContainsVar

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/FunctionalTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Persisters/PersistenceBuilderTest.php
- tests/Documents/CmsComment.php
- tests/Documents/UserUpsert.php
- tests/Documents/UserUpsertIdStrategyNone.php
Based on the feedback on #1761, the handling for upserting fields with a null value is correct: `null` values should never overwrite pre-existing data in upsert queries, since the document being upserted is in an unknown state and we can't know for certain that the value should be unset.
This PR brings this same behavior to fields with the `nullable` attribute set, where an upsert would always overwrite database values with a `null` value: this is now only done if the upsert results in an insertion, thus preserving pre-existing data but ensuring the normal behavior of the `nullable` flag is preserved.
> Fix upsert handling of nullable fields

- CHANGELOG-1.2.md
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/FunctionalTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Persisters/PersistenceBuilderTest.php
- tests/Documents/CmsComment.php
- tests/Documents/UserUpsert.php
- tests/Documents/UserUpsertIdStrategyNone.php
Cherry-pick from #1764 for 2.0.
> [2.0] Fix upsert handling of nullable fields

- .github/ISSUE_TEMPLATE/BC_Break.md
- .github/ISSUE_TEMPLATE/Bug.md
- .github/ISSUE_TEMPLATE/Feature_Request.md
- .github/ISSUE_TEMPLATE/Support_Question.md
- .github/PULL_REQUEST_TEMPLATE.md
Issue templates taken from https://github.com/doctrine/doctrine2/pull/7216.
PR templates are not working the same way (yet?) so for now I added one in _legacy_ format (` .github/PULL_REQUEST_TEMPLATE.md `).
> Add GitHub issue and PR templates

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/OrphanRemovalTest.php
When `orphanRemoval` is enabled on a reference, the referenced object is removed as soon as it no longer belongs to a parent. However, this also means that it needs to be dropped when the parent no longer exists. This is normally achieved by cascading `remove` operations in the reference mapping, but in case if `orphanRemoval` is set, we need to implicitly assume that remove operations need to be cascaded to the referenced object.
> Implicitly cascade remove operations when orphanRemoval is enabled

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php
- tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
- tests/Documents/IndirectlyReferencedUser.php
- tests/Documents/ReferenceUser.php
| Fixed issues | #1723
While fixing #1723 it turned out that querying any reference-structure is producing wrong query (like `_id` instead of `$id` in a `DBRef` object). This should be fixed now, at least when references are in embedded documents.
> Fix querying fields in reference structures

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php
- tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
- tests/Documents/IndirectlyReferencedUser.php
- tests/Documents/ReferenceUser.php
Closes #1794. Cherry-pick of #1793 for 2.0.
> [2.0] Fix querying fields in reference structures

- docs/en/reference/basic-mapping.rst
- docs/en/reference/capped-collections.rst
- docs/en/reference/xml-mapping.rst
- docs/en/tutorials/getting-started.rst
- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH774/Doctrine.ODM.MongoDB.Tests.GH774AbstractThread.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.InvalidPartialFilterDocument.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.PartialFilterDocument.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.PrimedCollectionDocument.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.User.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.UserCustomIdGenerator.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.UserNonStringOptions.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
| Fixed issues | #1806 
This PR extracts identifier options from the `field` tag in the XML mapping and moves it to a new `id` field. This is done to make it easier to map identifiers and to have fewer incompatibilities to take care of (e.g. it doesn't make sense to specify generator options on non-identifier fields and identifiers can't take many of the options available to regular fields). It also brings identifier mappings more in-line with what we're planning to do with GridFS fields (see #1790).
Note: this change needs to be backported to 1.3, along with a deprecation warning about `id="true"` being removed in 2.0.
> [2.0] Separate ID mapping from fields in XML driver

- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
| Fixed issues | #1821
Improved comparison logic should avoid rebuilding text indexes unnecessarily, as reported in #1821. This likely needs to be cherry-picked up to master after the merge to 1.2.x.
> Improve SchemaManager logic for comparing text indexes

- lib/Doctrine/ODM/MongoDB/Query/Expr.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Query/ExprTest.php
Fixes #1830 and is a port of https://github.com/doctrine/mongodb/pull/326 which fixes this problem for ODM 1.x.
> [2.0] Fix wrong element deletion in popFirst and popLast

- lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
- lib/Doctrine/ODM/MongoDB/Configuration.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Query/Builder.php
- lib/Doctrine/ODM/MongoDB/Query/Expr.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/DropCommand.php
- lib/Doctrine/ODM/MongoDB/Types/CustomIdType.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
Together with PHPStorm and https://github.com/kalessil/phpinspectionsea, here are some improvements that we can make to MongoDB ODM, such as unnecessaries parentheses, casts; null coalesce operator usage; in_array instead of array_search + comparison, etc
> Improvements

- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
- lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/XmlDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.UserNonStringOptions.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/XmlMappingDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.InvalidMappingDocument.dcm.xml
With this change, invalid XML mapping files are no longer accepted by the XML driver. It also replaces the pesky `sequence` element in the schema with `choice`, allowing fields in any order the user wants to map them. This mirrors a change done in ORM a while ago.
Last but not least, this removes leftover handling for the `id` attribute in the `field` mapping that should have been removed in #1807.
When backporting this feature to 1.3, we have to introduce a strict mode for mapping files that is disabled by default. When disabled, it will trigger a deprecation warning to inform the user that it will  throw exceptions in 2.0; when enabled, it will behave like the driver in 2.0 and throw …
> [2.0] Validate mapping files against schema

- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
I've noticed this while reviewing GridFS changes ([reference](
https://github.com/doctrine/mongodb-odm/pull/1790#discussion_r203134914)) and decided to update the names consistently. We'll create a BC layer for this introducing the `field-name` and `write-concern` attributes preferring them over the old names if both are set. Additionally, using `fieldName` and `writeConcern` will cause a deprecation warning to be thrown in 1.3.
> [2.0] Consistently use kebab-case in XML mappings

- .travis.yml
- composer.json
> [2.0] Require php : ^7.2

- tests/Doctrine/ODM/MongoDB/Tests/PersistentCollection/DefaultPersistentCollectionGeneratorTest.php
| Fixed issues | partial #1791
> [2.0] Test update: ODM no longer supports PHP < 7.2

- composer.json
- tests/Doctrine/ODM/MongoDB/Tests/Query/ExprTest.php
- tests/Documents/IndirectlyReferencedUser.php
Fixes failing build due to a broken test and an invalid `strict_types` declaration.
> [1.2] Fix failing build

- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
As per #1699.
Note to merger: please change target branch to 1.3.x!
> Deprecate combining repositoryMethod with skip, sort and limit

- .travis.yml
- composer.json
- docs/en/reference/sharding.rst
- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/EnsureShardingTest.php
- tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
- tests/Documents/Developer.php
- tests/Documents/Sharded/ShardedOne.php
- tests/Documents/Sharded/ShardedOneWithDifferentKey.php
| Fixed issues | #1698 
This PR re-introduces full sharding support to ODM 2.0. Due to changes in the server, the implementation now requires the user to map an index covering the shard key. Previously, this index was created automatically by ODM based on an index suggestion returned by the server as a response to the `shardCollection` command. Since this is no longer returned, we can't implicitly create an index without duplicating the index check logic in the server. Thus, we require the user to create the index themselves.
A compat layer for 1.3 should ideally warn the user about the change when an index is implicitly created when enabling sharding for a collection.
> Finalize sharding support for 2.0

- docs/en/cookbook/resolve-target-document-listener.rst
- docs/en/reference/eager-cursors.rst
- docs/en/reference/events.rst
- docs/en/reference/introduction.rst
- docs/en/tutorials/getting-started.rst
- lib/Doctrine/ODM/MongoDB/DocumentManager.php
- lib/Doctrine/ODM/MongoDB/MongoDBException.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/DocumentManagerTest.php
| Fixed issues | #1869
Fixes #1869 by enforcing the correct typeMap when a client is provided to the document manager. Since the typeMap can't (and most likely, shouldn't) be changed after instantiation of the client, we throw an exception if the typeMap isn't what we expect. For convenience, we also expose the expected typeMap using a constant for people to use. It also includes changes from #1870.
Furthermore, the documentation was updated to remove some legacy types.
> Enforce typemap

- docs/en/reference/aggregation-builder.rst
After spending some hours trying to figure out why I had the error "can't convert from BSON type string to Date" I founded that there is an error in the doc
"->month('purchaseDate')" and "->year('purchaseDate')" instead of "->month('$purchaseDate')" and "->year('$purchaseDate')"
| Type         | bug/feature/improvement
| BC Break     | yes/no
| Fixed issues |
> Error in group aggregation builder

- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
- lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
- tests/Doctrine/ODM/MongoDB/Tests/DocumentManagerTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
| Fixed issues | #1854 
The `simple` option for references has been dropped in favour of the `storeAs` directive, so it makes sense to drop this from the schema. This PR also updates the wording in some exception messages to no longer refer to these references as "simple" but rather "identifier references".
> Drop "simple" attribute from references in XML schema

- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/QueryCommand.php
The `dump` function from the root namespace may conflict with other packages, e.g. `nette/tracy`. Thus, we always use the `VarDumper::dump` method to ensure we're calling what we expect to call.
> Always use dump method from VarDumper component

- UPGRADE-2.0.md
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/QueryCommand.php
The query command uses the Symfony VarDumper component to dump query output to the user. By default however, the dumper dumps this to stdout. This PR uses a custom dumper to instead dump to the console output.
This also adds missing documentation for the BC break introduced in #1896 (the `--depth` option was dropped).
> Don't dump to stdout in query command

- lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/CollectionPersisterTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/LockTest.php
Implemented CollectionPersister::deleteAll method for simultaneous deletion of collections that is belong to one document.
Improved removal of scheduled for removal collections. Now all collections that is belong to one parent is deleted in one query.
> Optimized nested collections deletion in DocumentPersister

- doctrine-mongo-mapping.xsd
| Fixed issues | --
The deprecated comment should be placed before the deprecated element.
In PhpStorm with the old placement, the `store-as` attribute was marked as deprecated instead of the `simple` attribute.
as discussed in #1895 and #1917
> Replace the deprecated comment

- doctrine-mongo-mapping.xsd
This fixes two wrong types in the mapping XSD that required people to write child elements in a certain order. This is inconsistent with the rest of the schema file.
> Fix wrong usage of sequence vs. choice in XSD

- docs/en/cookbook/mapping-classes-to-orm-and-odm.rst
- docs/en/reference/aggregation-builder.rst
- docs/en/reference/basic-mapping.rst
- docs/en/reference/capped-collections.rst
- docs/en/reference/indexes.rst
- docs/en/reference/reference-mapping.rst
- docs/en/reference/storing-files-with-mongogridfs.rst
- docs/en/reference/transactions-and-concurrency.rst
- docs/en/reference/xml-mapping.rst
- docs/en/tutorials/getting-started.rst
- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverFile.dcm.xml
An unfortunate BC break, looks like we didn't properly clean up GridFS attribute names before merging the PR, which is why we have to change some more `writeConcern` and `fieldName` attribute names.
This PR also updates these in the documentation which was omitted before.
> Fix wrong capitalisation of attributes for GridFS mappings

- UPGRADE-1.3.md
- docs/en/reference/annotations-reference.rst
- docs/en/reference/indexes.rst
- docs/en/reference/migrating-schemas.rst
- docs/en/reference/query-builder-api.rst
- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/DocumentManager.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractField.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractIndex.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/NotSaved.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
- lib/Doctrine/ODM/MongoDB/Query/Builder.php
- lib/Doctrine/ODM/MongoDB/Query/Query.php
- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/AbstractCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/AlsoLoadTest.php
- tests/Documents/File.php
- tests/Documents/Functional/NotSaved.php
- tests/Documents/Functional/NotSavedEmbedded.php
After #1924, this adds some more deprecations for 2.0:
* Deprecate partial discriminator maps; references must now define all possible classes in discriminator maps if they have a map (#1887)
* Deprecate the `eagerCursor` helper in `Query\Builder` and the `eager` option in `Query\Query` (#1902)
* Deprecate the `@NotSaved` annotation (#1903)
* Deprecate multiple fields with the same name in the database (#1903)
* Deprecate using multiple class-level document annotations in mappings (#1906)
* Deprecate `timeout` option in schema commands (#1910)
* Deprecate `dropDups` option in indexes (#1910)
* Deprecate `indexOptions` arguments in SchemaManager (#1910)
> Deprecate more features in preparation for 2.0

- lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
- tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
| Fixed issues | Fixes #1864, Replaces #1914
This ensures that any internal data from `PersistentCollection` instances are serialised to have a usable collection instance after serialisation. This affects the `mongoData` and `snapshot` properties along with `isDirty` and `hints`.
Ping @watari
> Fix serialisation of uninitialised PersistentCollection instances

- lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
- tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
| Fixed issues | #1864 
Ports #1929 to ODM 2.0.
> [2.0] Fix serialisation of uninitialised PersistentCollection instances

- .github/stale.yml
This adds configuration for [stalebot](https://github.com/apps/stale). We mark issues as stale after 30 days and close them after a further 7, with these values being subject to change if we notice it's too aggressive.
Bugs, and Issues/PRs that have been added to a Project or Milestone will not be closed.
> Add configuration for stalebot

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
| Fixed issues | no
This line is not required anymore as we now have PHP 7.2 as min. version.
I did not test this apart from making sure the file can still be parsed. Not sure if that is required or how to accomplish that.
> Removed PHP 5.5 workaround

- lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
| BC Break     | yes?
| Fixed issues | no, but TODO in code
Saw this @todo in the code and thought I might aswell just fix it.
These names are now the same as in the ORM.
I guess this is a BC break if people used the UOW directly, should this change be included in the Upgrade/Changelog? (#1696)
> Renamed scheduledForDirtyCheck

- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateHydratorsCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GeneratePersistentCollectionsCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php
| Fixed issues | #1943
The $filter input option from the generate commands should be asserted as array instead of string.
> fix: replace string assertion with array assertion for $filter

- lib/Doctrine/ODM/MongoDB/PersistentCollection/DefaultPersistentCollectionGenerator.php
- lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
This backports #1938 and #1942 to 1.3 and adds the corresponding deprecation notices.
> [1.3] Rename scheduleForDirtyFlag

- docs/en/reference/aggregation-builder.rst
Lookup is not working with `embedDoc.refDocs`. (ReferenceOne and Many) It's not really a problem because when passing refDoc::class in lookup and manually setting localField, foreignField, it's working great.
I just wrote some documentation for it and added an Exception (thrown error wasn't understandable)
Plus, the simple `lookup()->alias()` with ReferenceMany seems not to work with Mongo 3.2. Which seems to be confirmed by the tests (https://github.com/doctrine/mongodb-odm/blob/1.2.x/tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/LookupTest.php#L191) but not indicated in doc, I added a line about that.
> Documenting Lookup not working on ref which are in embedded doc.

- UPGRADE-1.3.md
- lib/Doctrine/ODM/MongoDB/Configuration.php
- lib/Doctrine/ODM/MongoDB/Proxy/Proxy.php
- lib/Doctrine/ODM/MongoDB/Proxy/ProxyFactory.php
This drops the proxy classes related to `doctrine/common`. Unfortunately we won't be able to provide a BC layer due to `ocramius/proxy-manager` 2.0 needing PHP 7.0. To avoid deprecation notices that users can't do anything about (see #1675) I didn't add any `trigger_error` calls to deprecated interfaces but those could certainly be added to `ProxyFactory` and `Proxy`.
> [1.3] Deprecate proxies from doctrine/common

- UPGRADE-1.3.md
- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/File.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
- lib/Doctrine/ODM/MongoDB/Types/FileType.php
| Type         | deprecation
This deprecates the current GridFS mapping to prepare users for the BC break in 2.0. A forward compatible layer can't be provided due to the differences in the underlying API (and because the work to do so would be unreasonable for the benefit provided).
> [1.3] Deprecate GridFS mappings

- UPGRADE-1.3.md
- lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/CollectionPersisterTest.php
This back ports #1880 to the 1.3 branch, deprecating the current method signatures of `delete` and `update` in the process.
> [1.3] Optimize nested collection deletions

- UPGRADE-1.3.md
> Clarify deprecation block for same-namespace resolution

- docs/en/reference/introduction.rst
- docs/en/tutorials/getting-started.rst
> Document autoload requirement for generated proxies

- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/EnsureShardingTest.php
- tests/Documents/Sharded/ShardedByUser.php
Schema manager should also know how to handle shard key on reference
This PR is part of sharding key on reference fix. Referencing another PR #1687
> Schema manager should handle shard key on reference

- .travis.yml
Support for MongoDB 3.2 ran out in September 2018 while we forgot to add 4.0 to the build pipeline. This PR corrects this and will also be applied to the 1.3 branch.
> Test against supported versions of MongoDB

- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1962Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
| BC Break     | Maybe
When having multiple levels of inheritance in your document structure, discriminator maps are inherited incorrectly. They are currently inherited from their parent class and cannot be overridden. As highlighted in the attached tests, fetching all documents from the `GH1962BarSuperclass` repository should only yield subclasses of that superclass but also returns an unrelated `GH1962FooDocument`, which should not happen.
In my opinion, discriminator maps should be overridable in a child class (as showcased in the test). Optionally, me may want to invert inheritance completely, where a discriminator map is not passed on to child classes but to parent classes; that way, a class will …
> Fix wrong usage of discriminator map in complex document inheritance chains

- lib/Doctrine/ODM/MongoDB/Aggregation/Stage.php
| Fixed issues | none
Introduces `addFields` method to `Stage` abstract, which was probably mistakenly omitted when `Stage\AddFields` was added.
> Add missing `addFields` method for Stage abstract

- docs/en/reference/annotations-reference.rst
- docs/en/reference/indexes.rst
- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1344Test.php
| Fixed issues | fixes #1344 
This fixes an issue when embedding a document containing a named index multiple times. Since the index had a name, this caused an exception with MongoDB since the index would already exist when creating it for the second embed use (see test case). With this change we're prefixing indexes pulled up from embedded documents with the name of the property that's embedding them. While this can cause exceptions when an index name becomes too long, the current solution gives more control to the user.
One option would be to add an `indexPrefix` option to embedded relationships and using that instead of the field name. Since that would be a new feature, I will not include it in …
> Fix embedding documents containing named indexes

- docs/en/reference/query-builder-api.rst
Clarifies the query builder documentation, stating that they'll both be removed in 2.0.
> Clarify deprecation of update() and multiple()

- .travis.yml
- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/EnsureShardingTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/ShardKeyTest.php
- tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
- tests/Documents/Sharded/ShardedOne.php
Discovered this while working on #1972: the root problem is also present in 1.2, where we should also fix it.
> [1.2] Fix sharding commands for MongoDB 4.0

- UPGRADE-2.0.md
- lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
- lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionInterface.php
- lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
- lib/Doctrine/ODM/MongoDB/Proxy/FileLocator.php
- lib/Doctrine/ODM/MongoDB/Query/QueryExpressionVisitor.php
- lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
See #1931 for details. I've added a note that we can also remove internal stuff in minor releases as I saw a number of methods that should not be added in the first place and I thought that we could remove them in 2.1 (such as `HydratorFactory::setUnitOfWork` which should be passed in ctor).
> Mark methods and classes as internal

- .travis.yml
* PHP 5.6 will be tested as part of the build against lowest dependencies
* Tests the currently supported MongoDB versions (3.4, 3.6, 4.0)
* Adds PHP 7.3 and 7.4snapshot (with allowed failures) to the build matrix
This change allows us to add more build stages for 1.3, e.g. the upcoming performance test suite 🎉
> [1.3] Use build stages in .travis.yml

- lib/Doctrine/ODM/MongoDB/Repository/DefaultGridFSRepository.php
- tests/Doctrine/ODM/MongoDB/Tests/Repository/DefaultGridFSRepositoryTest.php
- tests/Documents/FileMetadata.php
| Fixed issues | Fixes #1985 
This fixes a bug where metadata submitted while uploading a file to GridFS would not be stored correctly. The test only checked for the existence of the metadata object but did not check whether its information was stored correctly.
Unfortunately, due to the mechanics of GridFS uploads not all operations work as you'd normally expect. For example, uploading a file to GridFS with a metadata object that contains a reference will not cascade any operations to the referenced object as the UnitOfWork is not flushed during the update operation.
> Fix metadata storage when uploading GridFS files

- lib/Doctrine/ODM/MongoDB/Proxy/Factory/StaticProxyFactory.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1990Test.php
| Fixed issues | Fixes #1990 
This took a little longer to figure out. The issue was neither with inverse references, repository methods, discriminators or anything else but only appears when proxy objects have been generated through the `generateProxyClasses` method due to invalid configuration of skipped properties.
> Fix generation of proxy classes

- .travis.yml
* Install libonig-dev as it is temporarily required for snapshot and nighly tests (see https://github.com/travis-ci/php-src-builder/pull/36)
> Fix tests against php 7.4snapshot

- composer.json
- docs/en/reference/events.rst
- lib/Doctrine/ODM/MongoDB/Event/OnClassMetadataNotFoundEventArgs.php
- lib/Doctrine/ODM/MongoDB/Events.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
- tests/Doctrine/ODM/MongoDB/Tests/Events/OnClassMetadataNotFoundEventArgsTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataFactoryTest.php
| Type         | feature/improvement
| Fixed issues | #1993 
* Introduce the `onClassMetadataNotFound` event along with its object
* Add support for the `onClassMetadataNotFound` event in `ResolveTargetDocumentListener`
> Introducing class metadata not found

- doctrine-mongo-mapping.xsd
| Fixed issues | Fixes #1980 
With 2.0, loading mapping files that don't validate against the provided XSD file are no longer loaded and cause an exception. In 1.3, such files will trigger a deprecation notice to inform the user of the upcoming restriction. However, some of the values that were accepted before are not considered valid, most notably discriminator values. This PR loosens the restriction for those types.
Technically, we can most likely do the same for many other attributes that use `NMTOKEN` right now, especially since those checks are not done for annotation mappings. However, I'd rather not completely open up the types for field names, as we'd most likely want to restrict …
> Loosen naming rules for discriminator values

- lib/Doctrine/ODM/MongoDB/Query/Query.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php
| Fixed issues | Fixes #1981 
This ensures that when not using update operators, the query does not attempt to run an updateOne or findOneAndUpdate operation. Instead, the replaceOne or findOneAndReplace operation must be run to avoid errors.
When using the "multiple" option on an update query in combination with a replacement document, the query class will now throw an error as there is no replaceMany functionality.
> Run appropriate query operations when replacing documents

- UPGRADE-1.3.md
- docs/en/cookbook/resolve-target-document-listener.rst
- lib/Doctrine/ODM/MongoDB/Tools/ResolveTargetDocumentListener.php
- tests/Doctrine/ODM/MongoDB/Tests/Tools/ResolveTargetDocumentListenerTest.php
| Type         | feature/improvement
| Fixed issues | #1993 
Note: needs changes from #1998. As long as that isn't merged, this PR will be unstable.
Change `ResolveTargetDocumentListener` to be an event subscriber instead of an event listener
> Change `ResolveTargetDocumentListener` to be an event subscriber instead of an event listener

- lib/Doctrine/ODM/MongoDB/Query/Query.php
- tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
| Fixed issues | #1808
Previously, find operations were unique in that they did not inherit generic options passed to the `Query::__construct()` via `Builder::getQuery()`. This makes find consistent with other operations and also adds tests for allowing query array options to override these generic options.
This also enabled users to pass driver-specific options to `Collection::find()` that may not be supported by the Builder API.
> Allow specifying generic options for Query find operations

- lib/Doctrine/ODM/MongoDB/DocumentManager.php
- lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2002Test.php
While working on #2002, I noticed that the detection logic wasn't quite right. So I expanded the failing test submitted by @josefsabl to cover more use cases to make sure we're getting the discriminator logic correct.
Note that this doesn't fix this bug for 2.0, as we need to adapt the logic there a little bit to cover for the (expected) exceptions. While debugging, I also noticed an issue where the `PersistenceBuilder` modifies the ClassMetadata which definitely shouldn't happen.
> Fix discriminator handling with partial discriminator maps

- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
- tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
| Fixed issues | #841 
This was extracted from #1910 to allow for a more in-depth discussion. This PR reworks index equivalency checks. Previously, when encountering an unknown index option, we would always consider the indexes equivalent even though they weren't. This PR reverses this behaviour and considers indexes different if they have a different set of options. We exclude some options from this check (e.g. `unique`) to consider indexes equivalent when one specifies the option with the default value while the other one doesn't specify the option at all.
> Rework index equivalency checks

- .travis.yml
- composer.json
This makes use of a PHPUnit feature which dumps the code coverage whitelist in a format understandable by Xdebug, which in turn greatly speeds up code coverage builds. Locally, I was able to get build times with coverage from ~17 minutes down to ~11 minutes.
I've bumped the required PHPUnit version to the lowest version supporting the feature and have not checked if we may drop some more versions due to the PHP requirement.
> Dump xdebug filter to improve code coverage build performance

- lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage.php
- tests/Doctrine/ODM/MongoDB/Tests/Aggregation/BuilderTest.php
This takes work done by @Steveb-p in #1974 and applies it to the master branch. As explained in https://github.com/doctrine/mongodb-odm/pull/1974#issuecomment-482083234, without a public `addStage` method in the pipeline stages we can't really make it public in the builder either since it would break the fluent interface, which might confuse people. In order to avoid having to do a new minor release of `doctrine/mongodb` just to make the method public, we move the feature to the 2.0 release.
> Make addStage Aggregation Builder method public

- docs/en/cookbook/mapping-classes-to-orm-and-odm.rst
| Type         | bug / naming improvement
There was an inconsistency in `BlogPost` entity namespace/class name, which I corrected to the best of my understanding. And, additionally, I changed names of Repository classes to make them more clear, i.e. by moving them out of `Doctrine` namespace and unifying  the structure of directories for `ORM` and MongoDB `ODM`.
> Some errors or confusing class names changed

- doctrine-mongo-mapping.xsd
As discussed in Slack I propose to loosen the index key name from `NMTOKEN` to `string`.
TL;DR: Sometimes field names have characters that aren't covered by NMTOKEN and setting an index on such a field becomes impossible. MongoDB has no problems with field names or indexes containing arbitrary characters (e.g. a `\`).
I have no idea how to write a test for that, though.
> relax naming rule for index key name

- docs/en/reference/indexes.rst
The order syntax is only relevant for single-field indexes, where the index is specified within a field mapping. Multi-field indexes should simply specify the ordering (e.g. "asc") as a value for the corresponding key.
This came up in https://github.com/mongodb/mongo-php-library/issues/627.
This isn't relevant for `master`, since YamlDriver was removed in 2.0; however, this change should likely be merged up to the `1.3.x` branch. I'll defer to @malarzm and @alcaeus if it's worth back-porting to `1.0.x` and `1.1.x`, since the drop-down in the documentation does allow one to view content for those branches.
> Fix `order` syntax for YAML index examples

- composer.json
- tests/Doctrine/ODM/MongoDB/Tests/Aggregation/BuilderTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/ReplaceRootTest.php
Since the upstream library was fixed, we need to adapt the tests to ensure they won't randomly fail.
> Fix ReplaceRoot aggregation stage tests

- lib/Doctrine/ODM/MongoDB/Aggregation/Stage/ReplaceRoot.php
- tests/Doctrine/ODM/MongoDB/Tests/Aggregation/BuilderTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/ReplaceRootTest.php
| Fixed issues | https://github.com/doctrine/DoctrineMongoDBBundle/issues/565
This ports the changes from https://github.com/doctrine/mongodb/pull/333 to the master branch which now includes the main logic. For 1.x, the fix is done in doctrine/mongodb, we just need to update the tests once a fix is released.
> [2.0] Fix wrong syntax for replaceRoot stage

- docs/en/reference/aggregation-builder.rst
| Fixed issues | #2047
Show how one can pass expression as array to `AggregationBuilder` to make use of operators that did not yet receive a wrapper method.
> Show how to pass expression as array

- docs/en/reference/embedded-mapping.rst
| Type         | documentation
EmbedMany uses `Collection` interface objects when loading, so to prevent issues with types I'd suggest always using `Collection`.
> Fix EmbedMany documentation samples

- .travis.yml
This fixes the build after updating to `ext-mongodb` 1.6.0 since retryable writes don't play nice with sharded clusters backed by standalone servers (which you shouldn't run in production anyways).
> Disable retryable writes on travis-ci

- doctrine-mongo-mapping.xsd
For ease to code xml mapping (on PHPStorm, at least), I just added the storage strategies in xsd file
https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/storage-strategies.html#storage-strategies
I don't know if this should be added into 1.1.x too.
Let me know what to do if it should.
Edit : Also, I'm not sure what doeas the `xs:restriction` element yet,so I just based my changed on the existing `reference-store-as` `simpleType`
> Add storage strategy in xsd

- .travis.yml
- .travis/setup_mo.sh
- .travis/setup_mongodb.sh
- phpunit.xml.dist
This PR covers improvements suggested by @jmikola in https://github.com/doctrine/mongodb-odm/pull/2056#pullrequestreview-286835097:
* Run tests on standalone servers, adding a build stage for sharded tests (which only runs sharing-specific tests for build speed) and replica sets (as it covers what we think is the most popular use-case
* Add note about ini settings required to get the legacy extension working on newer MongoDB server version.
> Follow-up tasks for build modernisation

- .travis.yml
- benchmark/BaseBench.php
- benchmark/Document/HydrateDocumentBench.php
- benchmark/Document/LoadDocumentBench.php
- benchmark/Document/StoreDocumentBench.php
- composer.json
- phpbench.json
- tests/bootstrap.php
This PR introduces a few basic performance benchmarks to compare the performance of `ext-mongo` vs. `ext-mongodb` + `mongo-php-adapter` in 1.3, and then `ext-mongodb` natively in 2.0. For now, we have three benchmarks around storing, loading and hydrating documents. I have yet to understand the reason for the change in https://github.com/doctrine/mongodb-odm/pull/1908/files#diff-2022fc4ba746afe6891859e465c4474bR219 but will add a benchmark for that as well.
At the moment, the `BaseBench` class duplicates code from the PHPUnit bootstrap - not sure if abstracting that makes sense at this time.
> Performance benchmark

- lib/Doctrine/ODM/MongoDB/APM/CommandLogger.php
- lib/Doctrine/ODM/MongoDB/APM/CommandLoggerInterface.php
This interface is necessary so the Symfony Bundle can allow registering multiple loggers for commands. This was brought up by @jmikola in https://github.com/doctrine/DoctrineMongoDBBundle/pull/569#discussion_r303586382.
> Introduce interface for command loggers

- .travis.yml
* Simplify usage of build steps to make this more consistent with the master branch
* Fix wrong version number in 4.0 build stage. This resulted in the default MongoDB version (currently 4.0.7) to be used on travis-ci
* Extract coverage to a separate build to speed up build times
* Add builds against all MongoDB versions supported by the PHP driver
This makes the build files for 1.3.x and master more consistent, with master then using this version of the build file and just adding the new code quality stages.
> Optimise build configuration

- lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
While looking at #2032, I realised that we don't trigger a deprecation warning when using an incomplete discriminator map for an embedded relationship. This PR rectifies this.
> Add missing deprecation notice for incomplete embedded associations

- doctrine-mongo-mapping.xsd
A small bubu in the XML mapping schema file caused `\DOMDocument::schemaValidate` to fail and `\Doctrine\ODM\MongoDB\Mapping\Driver\XmlDriver::validateSchema` therefore triggers a deprecation warning.
This is already fixed in the `2.0.0-RC2` branch.
> fix an error in the XML schema

- docs/en/reference/xml-mapping.rst
Hi,
I believe the example for `SimplifiedXmlDriver` is wrong, the keys/values are flipped. [SymfonyFileLocator](https://github.com/doctrine/persistence/blob/2ae45c1436572dbcb1036801793b8b726c6a9f53/lib/Doctrine/Common/Persistence/Mapping/Driver/SymfonyFileLocator.php#L84) uses the keys as paths, see that `array_keys($prefixes)`?
```php
public function addNamespacePrefixes(array $prefixes)
{
$this->prefixes = array_merge($this->prefixes, $prefixes);
$this->paths    = array_merge($this->paths, array_keys($prefixes));
}
```
I would expect namespace prefix to be a key as well, but it's not the case. For instance the following code is not working:
```yaml
prefixes:
HelloFresh\MenuService\Domain\Menu: …
```
> Flipped key/value for SimplifiedXmlDriver example

- UPGRADE-2.0.md
- lib/Doctrine/ODM/MongoDB/DocumentManager.php
- lib/Doctrine/ODM/MongoDB/Proxy/Resolver/CachingClassNameResolver.php
- lib/Doctrine/ODM/MongoDB/Proxy/Resolver/ClassNameResolver.php
- lib/Doctrine/ODM/MongoDB/Proxy/Resolver/ProxyManagerClassNameResolver.php
cc @watari
#1908 suggests a number of changes to improve document performance. I was especially curious about the changes to the document manager, where an additional cache for `ClassMetadata` is added. Looking at that change in isolation, it turns out that most of the improvements to the performance test suite come from that single change.
Upon further investigation, I was able to pinpoint the performance regression to the class name resolution for proxy objects, which now was added to MongoDB ODM until the doctrine/persistence layer supports multiple proxy implementations.
This PR removes this issue by adding a caching version of a class name resolver which removes the …
> Class name resolver performance optimisation

- lib/Doctrine/ODM/MongoDB/Hydrator/HydratorException.php
- lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/HydratorTest.php
| Fixed issues | #2044 
This adds type checks for associations to the hydrator, to prevent errors when receiving invalid data from the database. For most associations, this resulted in a `TypeError` being thrown, but for references this could result in invalid offsets when accessing the reference "array".
To fix this problem, there are new `HydratorException` methods to account for these errors. We print the class name, field name of the offending data, as well as the expected and actual types. Since we are in the middle of hydration, we can't reliably print a full field path (we don't know if this is a root hydration or already within an embedded document), which also means that we can't print an …
> Throw hydrator exceptions when encountering invalid types

- docs/en/reference/capped-collections.rst
This PR adds the command to use when using Doctrine with Symfony to create a _capped collection_. 
I spent some time on debugging what exactly needs to be done to have Doctrine listen to the capped collection configuration and it was missing from the documentation.
> Add command example to create a capped collection

- tests/Doctrine/ODM/MongoDB/Tests/Functional/EmbeddedTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/LockTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/NestedDocumentsTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/RepositoriesTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH245Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Repository/DefaultGridFSRepositoryTest.php
- The method `assertInternalType()` is deprecated, use alternatives such as `assertIsInt()`. https://github.com/sebastianbergmann/phpunit/issues/3369
- The `$delta` parameter of `assertEquals()` is deprecated, use `assertWithDelta()` instead. https://github.com/sebastianbergmann/phpunit/issues/3341
> Use alternatives for features deprecated in PHPUnit 8

- docs/en/reference/basic-mapping.rst
- docs/en/reference/custom-mapping-types.rst
- docs/en/sidebar.rst
> Move custom type to a separate chapter

- lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
- tests/Doctrine/ODM/MongoDB/Tests/HydratorTest.php
| Fixed issues | Fixes #2080 
This fixes an issue where hydrating a proxy object will not initialise any properties that aren't passed to the hydrator. With this fix, we invoke proxy initialisation with an empty initialiser so we initialise an empty object before adding any data.
> Fix wrong initialisation of proxies with public properties

- UPGRADE-2.0.md
- docs/en/reference/query-builder-api.rst
Looks like something that was missed in the 2.x changes; `execute()` no longer returns a cursor but an `Iterator`, and `distinct()` returns a plain array.
I do wonder if there should be an additional note for `distinct()` calling out that the returned type is different, since that can be a bit jarring (I was migrating a project and it took me a minute to understand exactly what was different here).
> Change returned type references in query builder documentation

- lib/Doctrine/ODM/MongoDB/Repository/DefaultGridFSRepository.php
- tests/Doctrine/ODM/MongoDB/Tests/Repository/DefaultGridFSRepositoryTest.php
- tests/Documents/FileWithoutChunkSize.php
| Fixed issues | Fixes #2087 
@jmikola The issue is caused by `mongodb/mongodb` using `isset` checks for options. When passing a `null` option, it will not be validated (as `isset` returns `false`) but still assigned. The `null` value is then interpreted as `0` in various places, leading to an endless loop of reading 0 bytes and not inserting an empty chunk. This is something we may want to address, so I've created [PHPLIB-494](https://jira.mongodb.org/browse/PHPLIB-494) to track this.
> Fix hanging upload when not specifying chunk size

- composer.json
- doctrine-mongo-mapping.xsd
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/AbstractDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/XmlDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/AlsoLoadDocument.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.AlsoLoadDocument.dcm.xml
Need to cast also-xml to string before calling explode as it is a SimpleXmlElement object otherwise a fatal error is thrown
> Cast also-load xml attribute to string

- lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/yaml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.yml
| Fixed issues | Fixes #2096 
This fixes an error where the `field-name` attribute in `id` XML mappings was not correctly mapped.
> Fix wrong handling of custom identifier names

- docs/en/reference/console-commands.rst
| Type         | Documentation update
Remove the documentation for odm:generate:documents and odm:generate:repositories commands which have been dropped since 2.0.
> [Doc] Remove dropped commands

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DetachedDocumentTest.php
| Fixed issues | Fixes #2106 
The described issue only appears when not cascading merge operations. The problem is that the call to `registerManaged` after creating a new proxy object will return early since a document with that ID is already registered (the original proxy loaded in `$managedCopy`. This leads to the new value for the association being different from the document that is being managed by the entity manager, which again causes issues on subsequent proxy initialisations.
On a related note, I'm not sure why the merge logic includes creating a new proxy object for the managed copy and discarding the changes from the original. However, this is logic that was introduced 8 years ago to ORM, …
> Fix merging of documents when not cascading references

- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DetachedDocumentTest.php
Release [1.3.4](https://github.com/doctrine/mongodb-odm/milestone/52)
1.3.4
=====
- Total issues resolved: **1**
- Total pull requests resolved: **1**
- Total contributors: **2**
Bug
---
- [2108: Fix merging of documents when not cascading references](https://github.com/doctrine/mongodb-odm/pull/2108) thanks to @alcaeus and @TheHett
> Merge release 1.3.4 into 2.0.x

- lib/Doctrine/ODM/MongoDB/DocumentManager.php
- lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
- lib/Doctrine/ODM/MongoDB/UnitOfWork.php
| Fixed issues | (partly) fixes #2122
This removes a few `@internal` designations for methods that aren't really internal, but where the comment was used to leave notes that shouldn't be exposed in an API documentation.
> Remove unneceesary internal designations

- docs/en/reference/annotations-reference.rst
- docs/en/reference/basic-mapping.rst
- docs/en/reference/transactions-and-concurrency.rst
- lib/Doctrine/ODM/MongoDB/LockException.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Types/DateImmutableType.php
- lib/Doctrine/ODM/MongoDB/Types/DateType.php
- lib/Doctrine/ODM/MongoDB/Types/Type.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/LockTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Types/DateImmutableTypeTest.php
| Fixed issues | #1975
As per title :)
> Add DateImmutable type

- docs/en/sidebar.rst
This removes conflict markers from the sidebar and adds a missing docs section back.
Thanks @TimoBakx for pointing this out to me!
> Remove conflict markers

- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateHydratorsCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GeneratePersistentCollectionsCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php
- lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateRepositoriesCommand.php
Some messages are rendered as `Hydrator classes generated to "path/to/my/project/var/pre-cached/Hydrators</INFO>"`.
Because the opening and closing tags are not case sensitive.
So i use `</info>` instead of `</INFO>` for these messages.
> FIX - info message must be lowercase

- docs/en/cookbook/blending-orm-and-mongodb-odm.rst
This applies my last remark to #2093 and I've changed literal class usage to `::class` notation.
> #2093 final touches

- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
| Fixed issues | Fixes #2147
When the `background` index option is missing from either the MongoDB or document index, the index is no longer considered the same. Since this option only refers to index creation, it should always be ignored entirely and not be a cause to recreate an index.
> Ignore missing background option when comparing indexes

- docs/en/cookbook/blending-orm-and-mongodb-odm.rst
- lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
Release [1.3.6](https://github.com/doctrine/mongodb-odm/milestone/54)
1.3.6
=====
- Total issues resolved: **1**
- Total pull requests resolved: **3**
- Total contributors: **3**
Documentation
-------------
- [2143: #2093 final touches](https://github.com/doctrine/mongodb-odm/pull/2143) thanks to @malarzm
BC Break,Bug
------------
- [2139: Change Throwable to Exception for PHP 5.6](https://github.com/doctrine/mongodb-odm/pull/2139) thanks to @malarzm and @AronSzigetvari
Bug
---
- [2131: FIX - info message must be lowercase](https://github.com/doctrine/mongodb-odm/pull/2131) thanks to @floverdevel
> Merge release 1.3.6 into 2.0.x

- lib/Doctrine/ODM/MongoDB/DocumentManager.php
We missed this originally. Patch also includes forward compatibility layer so consumers may pass `$options` as a first argument already. Also there's a chance I should have placed similar code in `UnitOfWork::commit` although I haven't thought about any legit reason to call it directly instead of `DocumentManager::flush` so I didn't bother
> Deprecation and forward compat for flush

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
| Type         | feature/improvement
| Fixed issues | #2103 
This PR adds conversion of PHP values in queries to their DB representations using types functionality, and thus allows to query by php values rather that db values.
> Added conversion from PHP values to DB values during query preparation

- docs/en/reference/query-builder-api.rst
| Type         | improvement?
| BC Break     | no?
When trying to do
```
->language('it')
->text('parole che stai cercando');
```
I get:
`This method requires a $text operator (call text() first)`
I assumed the docs was wrong. If I am somehow not understanding this, please feel free to close the PR.
> Chaged the Text Search docs on language

- docs/en/sidebar.rst
| Fixed issues | no
Link on "Reference Mapping" not exists in sidebar
> Link on "Reference Mapping" not exists in sidebar

- tests/Doctrine/ODM/MongoDB/Tests/Functional/ReadPreferenceTest.php
Fixes a test that randomly fails due to reading from secondaries. While a majority write concern doesn't eliminate reading from a stale secondary, the only way to do so was to check how many healthy nodes the replica set in question has and using that for write concern. I'll take a significantly reduced number of failures over the current state anytime.
> Use majority write concern to fix flaky test

- UPGRADE-2.1.md
- lib/Doctrine/ODM/MongoDB/Id/AbstractIdGenerator.php
- lib/Doctrine/ODM/MongoDB/Id/IdGenerator.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
There's no reason to provide an abstract class instead of an interface. Since this is a BC break I propose we do this for 2.0 although I'm eager to deprecate the class in 1.3 and remove the abstract in 2.0 already :)
> [2.1] Deprecate AbstractIdGenerator

- composer.json
- docs/en/reference/annotations-reference.rst
- docs/en/reference/basic-mapping.rst
- docs/en/reference/storage-strategies.rst
- docs/en/reference/transactions-and-concurrency.rst
- lib/Doctrine/ODM/MongoDB/LockException.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
- lib/Doctrine/ODM/MongoDB/Types/Decimal128Type.php
- lib/Doctrine/ODM/MongoDB/Types/FloatType.php
- lib/Doctrine/ODM/MongoDB/Types/Incrementable.php
- lib/Doctrine/ODM/MongoDB/Types/IntType.php
- lib/Doctrine/ODM/MongoDB/Types/Type.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/FunctionalTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/LockTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverViewWithWrongRepository.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverViewWithoutRepository.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Types/TypeTest.php
- tests/Documents/User.php
| Fixed issues | #1835
As per title, again ;)
> Add Decimal128 type

- UPGRADE-2.1.md
- docs/en/cookbook/blending-orm-and-mongodb-odm.rst
- docs/en/cookbook/mapping-classes-to-orm-and-odm.rst
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/Types/Type.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/AbstractDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.QueryResultDocument.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.View.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
- tests/Doctrine/ODM/MongoDB/Tests/Persisters/DocumentPersisterGetShardKeyQueryTest.php
> Favour bool and int over boolean and integer

- docs/en/reference/annotations-reference.rst
- docs/en/reference/transactions-and-concurrency.rst
- lib/Doctrine/ODM/MongoDB/LockException.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- lib/Doctrine/ODM/MongoDB/Types/DateImmutableType.php
- lib/Doctrine/ODM/MongoDB/Types/DateType.php
- lib/Doctrine/ODM/MongoDB/Types/Decimal128Type.php
- lib/Doctrine/ODM/MongoDB/Types/IntType.php
- lib/Doctrine/ODM/MongoDB/Types/Versionable.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/LockTest.php
> Introduce Versionable interface

- composer.json
- lib/Doctrine/ODM/MongoDB/DocumentManager.php
This uses a new option in the upcoming MongoDB driver to provide additional driver metadata. The new feature allows custom drivers (such as ODMs) to add their own metadata to the initial MongoDB handshake. This allows for a more detailed analysis of driver versions being used.
Note that this PR doesn't bump the required driver version on purpose: if the driver doesn't support this option, it doesn't throw an error but ignore the option. Furthermore, as ext-mongodb 1.8 is not released yet, I don't want to tie the ODM release schedule to that of the MongoDB driver.
> Append ODM version info to driver metadata

- UPGRADE-2.1.md
- lib/Doctrine/ODM/MongoDB/Id/AbstractIdGenerator.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/Types/IntIdType.php
- lib/Doctrine/ODM/MongoDB/Types/Type.php
- tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
> Favour int over int_id

- lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Facet.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2157Test.php
| Fixed issues | #2157 
Provide a bool flag for `getPipeline()` if it's being called from inside the `Facet` and test case with `DiscriminatorMap` annotated document.
> Bug/2157 Test (and fix) Facet's aggregation pipeline with DiscriminatorMap documents

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
| Fixed issues | N/A
Following https://github.com/doctrine/mongodb-odm/pull/2104.
In API Platform, since the release of the 2.1 version, the following test was failing: https://github.com/api-platform/core/blob/d83d50228e2686b7a2f76bfbadf2dec3fd83fdcd/tests/Bridge/Doctrine/MongoDbOdm/Filter/DateFilterTest.php#L264-L289
You can see it here: https://github.com/api-platform/core/pull/3571/checks?check_run_id=718581504 and here: https://github.com/api-platform/core/pull/3571/checks?check_run_id=718581453.
It's because https://github.com/doctrine/mongodb-odm/pull/2104 has removed the `array_map` on the `$preparedValue`: `DateTime` is not converted anymore to the DB type if it is the type of a value in an …
> Fix prepareQueryOrNewObj with object values

- lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
| Fixed issues | #2193, #2194, #2199
> Stop type conversion for certain keys in query

- UPGRADE-2.1.md
- UPGRADE-2.2.md
- UPGRADE-3.0.md
- docs/en/reference/aggregation-builder.rst
- lib/Doctrine/ODM/MongoDB/Aggregation/Aggregation.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage.php
- tests/Doctrine/ODM/MongoDB/Tests/Aggregation/BuilderTest.php
This introduces a new `Aggregation` class, that can be created from an aggregation builder using the `getAggregation` method. The `execute` method on the aggregation builder has been deprecated in favour of the new API.
The query builder returns a query instance that can be passed around without executing the query, but also disallowing changes to the query. The aggregation builder on the other hand only returns an iterator that may or may not have already executed something on the database. Passing the aggregation builder around opens it up to modification that may not be intended.
> Introduce aggregation API to replicate query API

- docs/en/reference/indexes.rst
The `safe` option is no longer supported by MongoDB and was dropped without replacement in 2.0 (see UPGRADE-2.0 document). This removes a left-over instance of that option in the documentation.
> Remove safe index option from documentation

- docs/en/reference/introduction.rst
The extension is required in composer.json, and its installation should
be mentioned because it will not even be possible to install the ODM
without it.
> Document requirement on PHP extension

- lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Bucket/AbstractOutput.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Group.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Match.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Operator.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Project.php
- lib/Doctrine/ODM/MongoDB/Query/Builder.php
- lib/Doctrine/ODM/MongoDB/Query/Expr.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/IdTest.php
Fixed links to mongodb manual
What does the PR do :
> Fix links to mongodb manual

- composer.json
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
It does not seem to be used in the code, nor in the commit that
introduced it, b05a8255124fe7c6ab3be8a53a816771a7b50ab7 . I picked improvement as the type because having an extra dependency will not cause any issue, and removing it might cause some if you use the lib in your application but forget to declare it in your Composer manifest.
> Remove unused dependency

- .github/workflows/static-analysis.yml
- .travis.yml
As requested in https://github.com/doctrine/mongodb-odm/pull/2231#issuecomment-715904404, this just moves the PHPStan check to GA.
Depends on https://github.com/doctrine/mongodb-odm/pull/2234/commits/54535fecb20035d21afbdb9e143a59ab8c5c52d1 to pass green.
> Migrate PHPStan job to GA

- UPGRADE-2.2.md
- docs/en/reference/annotations-reference.rst
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Indexes.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
| BC Break     | no (yet)
PHP 8.0's native attributes are not supporting nested attributes like doctrine annotations did. The only nested annotation in the ODM is an `@Index` which already could be used on a class-level, but wasn't advertised as such in the docs. The PR updates documentation and makes specifying `@Index` annotations on class level a recommended way to go deprecating other ways of doing so.
> Document class-level Index annotations and deprecate other ways of specifying them

- .github/workflows/static-analysis.yml
The phpstan version used (0.10.x)  does not work with the error
formatter, this just removes it and it will be added in another
commit upgrading PHPStan.
I used _improvement_ as I'm not sure about the type.
> Remove phpstan error formatter

- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
| Fixed issues | _none_
`trigger_error` should emit a E_USER_DEPRECATED error when a deprecated mapping type is used instead of the default error level.
> Fix trigger_error level when deprecated type is used

- tools/sandbox/config.php
| Fixed issues | #2245
Removes the reference to the `Doctrine\MongoDB\Connection` class from the archived https://github.com/doctrine/mongodb driver repository.
> Fix sandbox using old Doctrine\MongoDB\Connection class

- composer.json
- lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
- lib/Doctrine/ODM/MongoDB/Aggregation/Stage.php
- lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractField.php
- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
This replaces manual calls to `@trigger_error` with `trigger_deprecation` from the `symfony/deprecation-contracts` package. This allows users to override the `trigger_deprecation` function to implement their custom logic.
Note that this PR drops deprecation functionality for field mapping annotations that were supposed to be dropped in 2.0. Since these methods are marked `@internal`, I have no problem dropping them in a minor release.
> Use symfony/deprecation-contracts to announce deprecations in code

- lib/Doctrine/ODM/MongoDB/SchemaManager.php
- tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
Signed-off-by: Christoph Grabenstein <christoph.grabenstein@sensiolabs.de>
| Fixed issues | #2257
The fix consist of two main changes:
* added a strict check of the `array_key`s of the index-key-arrays.
* added a method that checks if the text indexes are at the same position.
> Added missing check for order of compound keys

- .github/workflows/continuous-integration.yml
- .github/workflows/static-analysis.yml
- lib/Doctrine/ODM/MongoDB/PersistentCollection/DefaultPersistentCollectionGenerator.php
- phpcs.xml.dist
- phpstan.neon.dist
- tests/Doctrine/ODM/MongoDB/Tests/PersistentCollection/CollWithPHP80Types.php
- tests/Doctrine/ODM/MongoDB/Tests/PersistentCollection/DefaultPersistentCollectionGeneratorTest.php
> Add support for PHP 8.0 types in custom collection

- .github/workflows/static-analysis.yml
- psalm.xml
Psalm is failing because if there is no php version specified, it uses the lower bound of composer, so if a library uses PHP 7.4+ syntax, it fails.
Ref: https://github.com/laminas/laminas-code/issues/67
> Run psalm with php 8

- lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH267Test.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
| Fixed issues | #2203
Based on #2213, this deprecates this invalid mapping. The discriminatorMap will be ignored entirely, but the mapping still works (but maybe not as people would expect). Despite that, I'm hesitant to make this an exception, so we're deprecating this for removal in 3.0.
> Deprecate mapping relations with targetDocument and discriminatorMap
