doctrine/mongodb-odm

tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH832Test.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH928Test.php
=> Add regression tests for non-reproducible bug reports

docs/en/reference/annotations-reference.rst
=> [doc] Fix typo

lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php, tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/XmlDriverTest.php, tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.UserNonStringOptions.dcm.xml
This fixes some parsing bugs I noticed while merging #997.
=> Fix parsing of non-string attributes in XML driver

CHANGELOG-1.0.md
1.0.0-BETA12 (2014-02-24) -> 1.0.0-BETA12 (2015-02-24)
=> Typo in CHANGELOG-1.0md

docs/en/reference/xml-mapping.rst
Documenting changes made for #674
=> Add note about XSD file versioning

lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php, lib/Doctrine/ODM/MongoDB/UnitOfWork.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH872/GH872Test.php
Fixes #872, closes #873  
/cc @vmattila
=> Fix embedded documents on inherited referenced documents

lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH850Test.php
=> Throw meaningful exception while referencing non-object

docs/en/reference/capped-collections.rst, doctrine-mongo-mapping.xsd, lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
=> Allow usage of capped collections via XML driver

lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php, lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
=> Do not set customRepository for EmbeddedDocument

tests/Doctrine/ODM/MongoDB/Tests/Functional/DateTest.php, tests/Doctrine/ODM/MongoDB/Tests/Mapping/Types/DateTypeTest.php
Added a test for issue #1060 
/cc @jmikola 
This is not a fix, but a temporary documentation while proper handling is added in the driver itself.
I added expected failures as well so we know when it is fixed.
=> Added test for 32/64-bit platforms for 1900 date

lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php, lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php, lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php, tests/Documents/Phonebook.php
Related to new functionality in #1096.
=> Fix handling of nested collections for atomic strategies

CHANGELOG-1.0.md
Documenting features in the [1.0.0-BETA13](https://github.com/doctrine/mongodb-odm/issues?milestone=7&q=is%3Aclosed) milestone.
=> Update changelog for 1.0.0-BETA13

lib/Doctrine/ODM/MongoDB/PersistentCollection.php, lib/Doctrine/ODM/MongoDB/UnitOfWork.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1132Test.php, tests/Documents/User.php
=> Fix usage of cloned PersistentCollection

lib/Doctrine/ODM/MongoDB/MongoDBException.php, lib/Doctrine/ODM/MongoDB/Types/CollectionType.php, lib/Doctrine/ODM/MongoDB/Types/HashType.php, tests/Doctrine/ODM/MongoDB/Tests/Types/InvalidValueExceptionTest.php
=> Added type checks for Collection and Hash types

.scrutinizer.yml, .travis.yml, README.markdown
This should generate code coverage and send report to [scrutinizer-ci](https://scrutinizer-ci.com/) for issue #1139 .
After an admin activate project in [scrutinizer-ci](https://scrutinizer-ci.com/) it will provide code analysis  and code coverage report for project.
=> #1139 - Add code coverage

tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH878Test.php
This is the test only for #878 which is fixed in #782.
PR is against this fix branch.
=> Test for #878

.travis.yml
http://docs.travis-ci.com/user/workers/container-based-infrastructure/
=> Use container-based infrastructure for travis builds.

lib/Doctrine/ODM/MongoDB/Types/DateType.php, tests/Doctrine/ODM/MongoDB/Tests/Mapping/Types/DateTypeTest.php
=> Add support for DateTimeImmutable in Date type

tests/Doctrine/ODM/MongoDB/Tests/Types/DateTypeTest.php, tests/Doctrine/ODM/MongoDB/Tests/Types/TypeTest.php
=> Add test for all types

lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/LockTest.php
Closes #1046 
~~I've got absolutely no idea how this could be tested so my word that it should work must do :baby:~~ Actually I'll write a test later, it's too hot and I forgot I can just test `CollectionPersister` ;)
=> Mind versioning when updating collections

lib/Doctrine/ODM/MongoDB/UnitOfWork.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH977Test.php
Rebase of #1131 atop 1.0.x branch, fixes #977
=> [1.0.x] Reuse previously calculate change set if available

tests/Doctrine/ODM/MongoDB/Tests/Mapping/Symfony/AbstractDriverTest.php
Cross referencing @Ocramius' https://github.com/doctrine/doctrine2/commit/e0148f14e2b9f6a477db6b7c73d378c66ec24132
=> Fix doctrine/common compatibility

lib/Doctrine/ODM/MongoDB/Event/PreUpdateEventArgs.php, lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php, lib/Doctrine/ODM/MongoDB/UnitOfWork.php, lib/Doctrine/ODM/MongoDB/Utility/LifecycleEventManager.php, tests/Doctrine/ODM/MongoDB/Tests/Events/PreUpdateEventArgsTest.php
Possibly first PR in a serie of making UnitOfWork a smaller and friendlier place. Frankly I was expecting to make performance a little bit worse but seen a gain instead (however running tests in vagrant may not be realiable perf-wise) - for sure it's not worse :)
=> Moved lifecycle callbacks/events logic

lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1346Test.php
Fixes #1347 
~~Marking as WIP as for some reason PHP segfaults on my local machine, let's see what Travis will say~~ - travis is fine, my machine will need an investigation of what's going on
=> Fix initializing lazy properties during hydration

.travis.yml, tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php, tests/sharded.json
Ok, now we're running tests on a sharded cluster, should be a good start for https://github.com/doctrine/mongodb-odm/pull/1025
=> Use mongo-orchestration on travis

lib/Doctrine/ODM/MongoDB/Tools/DocumentGenerator.php
In the same vein as doctrine/mongodb#251.
=> Corrected fluent interface docblock generation

lib/Doctrine/ODM/MongoDB/DocumentRepository.php
Made some rudimentary code and documentation quality improvements.
=> DocumentRepository code quality improvements.

CHANGELOG-1.0.md, lib/Doctrine/ODM/MongoDB/UnitOfWork.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1428Test.php
=> Fix field name usage when fixing embedded document ownership

docs/en/reference/events.rst, docs/en/reference/query-builder-api.rst, docs/en/reference/reference-mapping.rst, docs/en/reference/xml-mapping.rst, docs/en/reference/yml-mapping.rst
So far this closes #1446, #1445, #1442 and a bit older #632
=> Improve docs

lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencesTest.php
Fixes #1456, supersedes #1457 and targets 1.0.x branch
=> Do not refresh documents when loading sorted collection

tests/Doctrine/ODM/MongoDB/Tests/Persisters/DocumentPersisterGetShardKeyQueryTest.php
Found some leftovers while working on #1471
=> [1.1] Change field annotations

.travis.yml, composer.json
This may (and probably) will be bumped more, but for now let's save good ol' Travis some cycles
=> [2.0] Bump PHP to 7.0

lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php, lib/Doctrine/ODM/MongoDB/UnitOfWork.php
=> [2.0] Remove deprecated argument from DocumentPersister::refresh

docs/en/reference/find-and-update.rst, docs/en/reference/query-builder-api.rst, lib/Doctrine/ODM/MongoDB/Query/Builder.php
Follows up https://github.com/doctrine/mongodb/pull/275 and closes https://github.com/doctrine/mongodb-odm/issues/1501
=> Introduce updateOne and updateMany to ODM's builder

docs/en/reference/introduction.rst
=> Add section about using PHP 7 to the documentation

docs/en/reference/query-builder-api.rst, lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php, lib/Doctrine/ODM/MongoDB/Query/Expr.php, tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
=> Fix, test and document modifying references with Builder

docs/en/reference/aggregation-builder.rst
Referenced to doctrine/mongodb-odm#1402
=> Add note when AggregationBuilder is available

docs/en/reference/events.rst
Events were changed sometime ago and actually have arguments
=> Fix invalid info about event arguments

docs/en/reference/annotations-reference.rst, docs/en/reference/xml-mapping.rst, docs/en/reference/yml-mapping.rst
=> Versioning and locking documentation

docs/en/reference/query-builder-api.rst
=> add info on hint() method

lib/Doctrine/ODM/MongoDB/EagerCursor.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractField.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Bin.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/BinCustom.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/BinFunc.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/BinMD5.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/BinUUID.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/BinUUIDRFC4122.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Bool.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Boolean.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Collection.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Date.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Float.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Hash.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Increment.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Int.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Integer.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Key.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/ObjectId.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Raw.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/String.php, lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Timestamp.php, lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php, lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php, lib/Doctrine/ODM/MongoDB/Query/Builder.php, lib/Doctrine/ODM/MongoDB/Query/FieldExtractor.php, lib/Doctrine/ODM/MongoDB/Query/Query.php, lib/Doctrine/ODM/MongoDB/SchemaManager.php, lib/Doctrine/ODM/MongoDB/Types/IncrementType.php
I think I've covered all places that make sense. Not sure about all types annotations - should each deprecated one trigger error in its constructor?
=> Trigger E_USER_DEPRECATED for deprecated features

docs/en/reference/document-repositories.rst, lib/Doctrine/ODM/MongoDB/DocumentRepository.php
See https://github.com/doctrine/mongodb-odm/pull/1601#discussion_r119143856 for the original discussion.
Please vote with 👍 and 👎
=> [RFC] Deprecate repositories' magic findBy and findOneBy

lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php, lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
Backport of #1628 for 1.1. Turns out I inadvertedly merged this down to master.
=> Don't generate proxy classes for embedded documents (1.1)

composer.json
=> Allow symfony 4 console in composer.json

UPGRADE-1.2.md, composer.json, lib/Doctrine/ODM/MongoDB/Repository/DefaultRepositoryFactory.php, tests/Doctrine/ODM/MongoDB/Tests/Mapping/yaml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.yml
This pull request adds an UPGRADE document for ODM 1.2 and adds a deprecation we missed. This document will evolve as remaining pull requests are merged.
=> Add upgrade document for ODM 1.2

docs/en/reference/reference-mapping.rst
To  be able to take use of both polymorphism and the ability to use $lookup in aggregations.
=> Recommend storeAs=ref in docs

README.markdown, docs/en/index.rst
Also I've removed IRC as we're abandoning the ship and moved SO up so it looks more "preferred"
=> Add a link to chat room on gitter

docs/en/index.rst
See: https://github.com/doctrine/mongodb-odm/pull/1694#discussion_r158069270
=> Fix link name for Stack Overflow

lib/Doctrine/ODM/MongoDB/Configuration.php, lib/Doctrine/ODM/MongoDB/DocumentManager.php, lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php, lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php, lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php, lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php, lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php, lib/Doctrine/ODM/MongoDB/SchemaManager.php, lib/Doctrine/ODM/MongoDB/UnitOfWork.php, tests/Doctrine/ODM/MongoDB/Tests/Mocks/UnitOfWorkMock.php
=> Use Null Coalesce Operator

lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php, lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/DropCommand.php, tests/Documents/Ecommerce/ConfigurableProduct.php
They can help us save some lines of code :put_litter_in_its_place:
=> Use array_filter and array_map

lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php, lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Match.php, lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Operator.php, lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Project.php, lib/Doctrine/ODM/MongoDB/Query/Builder.php, lib/Doctrine/ODM/MongoDB/Query/CriteriaMerger.php, lib/Doctrine/ODM/MongoDB/Query/Expr.php, lib/Doctrine/ODM/MongoDB/Query/Query.php, tests/Doctrine/ODM/MongoDB/Tests/Query/ExprTest.php
ping @carusogabriel
Helps with #1702 and #1714.
=> Use proper variadic arguments

doctrine-mongo-mapping.xsd
Some things I've noticed that are off while working on #1730
=> Fix XSD shortcomings

.travis.yml, composer.json, lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php, lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php, lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Match.php, lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Operator.php, lib/Doctrine/ODM/MongoDB/DocumentManager.php, lib/Doctrine/ODM/MongoDB/Iterator/CachingIterator.php, lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php, lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php, lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionException.php, lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php, lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php, lib/Doctrine/ODM/MongoDB/Query/Builder.php, lib/Doctrine/ODM/MongoDB/Query/Expr.php, lib/Doctrine/ODM/MongoDB/Query/FilterCollection.php, lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php, lib/Doctrine/ODM/MongoDB/SchemaManager.php, lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/ValidateCommand.php, lib/Doctrine/ODM/MongoDB/Tools/ResolveTargetDocumentListener.php, lib/Doctrine/ODM/MongoDB/UnitOfWork.php
This starts #1701 by adding `PHPStan` :man_technologist:
=> Add PHPStan

lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php, lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php, tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
=> [2.0] Forbid combining repositoryMethod with skip, sort and limit

.travis.yml
This one runs for the longest time and blocks Code Quality while they could go in parallel.
=> Move coverage to Code Quality stage

docs/en/index.rst, docs/en/sidebar.rst
This depends on https://github.com/doctrine/doctrine-website/pull/88
=> Add sidebar.rst and cleanup docs homepage.

lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1775Test.php
Cherry-pick of #1784 into master branch.
=> [2.0] Fix hydration of proxy objects with lazy public properties

docs/en/cookbook/blending-orm-and-mongodb-odm.rst, docs/en/cookbook/implementing-array-access-for-domain-objects.rst, docs/en/cookbook/implementing-the-notify-changetracking-policy.rst, docs/en/cookbook/mapping-classes-to-orm-and-odm.rst, docs/en/cookbook/resolve-target-document-listener.rst, docs/en/cookbook/simple-search-engine.rst, docs/en/cookbook/soft-delete-extension.rst, docs/en/cookbook/validation-of-documents.rst, docs/en/reference/basic-mapping.rst, docs/en/reference/bidirectional-references.rst, docs/en/reference/change-tracking-policies.rst, docs/en/reference/complex-references.rst, docs/en/reference/custom-collections.rst, docs/en/reference/document-repositories.rst, docs/en/reference/events.rst, docs/en/reference/filters.rst, docs/en/reference/introduction.rst, docs/en/reference/migrating-schemas.rst, docs/en/reference/reference-mapping.rst, docs/en/reference/storing-files-with-mongogridfs.rst
This is some partial update of the docs with type hinting in code; related to #1783  . I've done only the cookbook to gather feedback.
=> Added type hinting to docs.

lib/Doctrine/ODM/MongoDB/UnitOfWork.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/OrphanRemovalTest.php
=> [2.0] Implicitly cascade remove operations when orphanRemoval is enabled

lib/Doctrine/ODM/MongoDB/Configuration.php
| Type         | cleanup
| Fixed issues | #1796 
Removed docblocks that seemed useless & added type hints where it was possible.
=> [2.0] Clean up docblocks in Configuration class - #1796

lib/Doctrine/ODM/MongoDB/Configuration.php
This PR follows #1799. Take a look at https://github.com/doctrine/mongodb-odm/pull/1799#discussion_r189278441
=> [2.0] Drop bool from supported values - Configuration class

.github/PULL_REQUEST_TEMPLATE.md
Added improvement type into pull request template
=> added improvement type into pull request template

tests/Doctrine/ODM/MongoDB/Tests/Functional/CustomIdTest.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM76Test.php
=> Use dedicated PHPUnit assertions

composer.json, tests/bootstrap.php
| Fixed issues | N/A
Follow up https://github.com/doctrine/mongodb-odm/pull/1825#issuecomment-408313167
=> Added dev autoload for composer & removed it from tests boostrap.

composer.json
=> [2.0] Upgrade dependencies version

.doctrine-project.json, composer.json
Add .doctrine-project.json to root of the project for the website build process.
=> Add .doctrine-project.json to root of the project.

docs/en/reference/xml-mapping.rst
Fix some typos in the documentation.
=> Fix fieldName with field-name

tests/Doctrine/ODM/MongoDB/Tests/Functional/DiscriminatorsDefaultValueTest.php
=> Use dedicated assertContainsOnlyInstancesOf assertion

lib/Doctrine/ODM/MongoDB/Configuration.php, lib/Doctrine/ODM/MongoDB/Proxy/FileLocator.php, tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
| Fixed issues | Fixes #1890 
Note: PR contains unrelated fixes when running test suite under mmapv1 as I was running into that by accident.
=> Fix missing proxy directory

lib/Doctrine/ODM/MongoDB/Mapping/Annotations/File.php, lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php, lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php, tests/Doctrine/ODM/MongoDB/Tests/Mapping/BasicInheritanceMappingTest.php
=> Fix inheritance of GridFS mapping properties

tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
=> Fix skipped tests

CHANGELOG-2.0.md
Putting this out here for sake of completeness. Thanks to everyone who helped get us to this point.
=> Update changelog for 2.0.0-Beta1

docs/en/reference/annotations-reference.rst
| Fixed issues | See 
https://github.com/doctrine/mongodb-odm/pull/1927#discussion_r247203273
=> Use same documentation for notSaved in all annotations

lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
=> Removed PHP 5.5 workaround

.travis.yml
=> [2.0] Add PHP 7.4snapshot to build pipeline

UPGRADE-2.0.md
=> [2.0] Add missing documentation of same-namespace resolution drop

composer.json
| Fixed issues | https://github.com/doctrine/mongodb-odm/issues/1957
Allow Symfony 3.4
=> Allow Symfony 3.4

lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1964Test.php
=> Fix wrong behavior of sortMeta 

lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php, tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
=> Allow returning null from getAssociationTargetClass

lib/Doctrine/ODM/MongoDB/Proxy/FileLocator.php
| Fixed issues | https://github.com/doctrine/mongodb-odm/issues/1995
=> Fix dir permissions for proxies

docs/en/reference/priming-references.rst
I wonder if there's anybody using custom primers :)
=> Update default reference primier's code

lib/Doctrine/ODM/MongoDB/Tools/Console/Command/ConvertMappingToXmlCommand.php
As we're going to kill YAML driver for 2.0 let's provide users with a command to convert their mappings to XML. I suggest to make this feature exclusive for 1.3 as I'm not really willing to maintain this :) Left to do:
=> Converter to XML for mapping

lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php, tests/Doctrine/ODM/MongoDB/Tests/Aggregation/BuilderTest.php
| Fixed issues | #2018 
Fixing IndexStats with used with discriminator field
=> Fixing  when used with discriminator field

lib/Doctrine/ODM/MongoDB/Iterator/CachingIterator.php, lib/Doctrine/ODM/MongoDB/Iterator/HydratingIterator.php
| Fixed issues | Fixes #2092 
The `CachingIterator` and `HydratingIterator` classes all wrap a given traversable in a generator. However, even when these iterators are garbage collected, the generator itself sometimes stays around and thus causes a memory leak. Thus, we remove our reference to the generator when destructing the iterators which allows freeing the underlying MongoDB cursor object.
=> Remove reference to generators on iterator destruction

docs/en/sidebar.rst
Type ->bug
remove basic mapping section which it was repeated
=> remove repeated sidebar section

docs/en/sidebar.rst
I went one by one with what's in directory and what's in the sidebar.
=> Add console commands and upserting chapters

composer.json, lib/Doctrine/ODM/MongoDB/Tools/Console/Command/ClearCache/MetadataCommand.php, lib/Doctrine/ODM/MongoDB/Tools/Console/Command/ConvertMappingToXmlCommand.php, lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateDocumentsCommand.php, lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateHydratorsCommand.php, lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GeneratePersistentCollectionsCommand.php, lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php, lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateRepositoriesCommand.php, lib/Doctrine/ODM/MongoDB/Tools/Console/Command/QueryCommand.php
=> Symfony 5 support

lib/Doctrine/ODM/MongoDB/DocumentManager.php, lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php, lib/Doctrine/ODM/MongoDB/UnitOfWork.php
Release [1.3.5](https://github.com/doctrine/mongodb-odm/milestone/53)
1.3.5
=====
- Total issues resolved: **0**
- Total pull requests resolved: **2**
- Total contributors: **2**
Enhancement
-----------
- [2123: Remove unneceesary internal designations](https://github.com/doctrine/mongodb-odm/pull/2123) thanks to @alcaeus
- [2115: Symfony 5 support](https://github.com/doctrine/mongodb-odm/pull/2115) thanks to @chalasr
=> Merge release 1.3.5 into 2.0.x

tests/Doctrine/ODM/MongoDB/Tests/Types/TypeTest.php
Few tests I've missed while originally working on `date_immutable`
=> More tests for date_immutable type

docs/en/reference/introduction.rst
=> Fix typo in setup documentation

lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
=> Change Throwable to Exception for PHP 5.6

lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php, tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php, tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverFileWithCustomRepository.dcm.xml
=> Fix reading custom repository class for GridFS XML mappings

composer.json
To include https://github.com/doctrine/persistence/pull/92
I'll release next 2.0.x after we merge this
=> Bump doctrine/persistence

composer.json, docs/en/cookbook/blending-orm-and-mongodb-odm.rst
Release [2.0.5](https://github.com/doctrine/mongodb-odm/milestone/56)
2.0.5
=====
- Total issues resolved: **0**
- Total pull requests resolved: **1**
- Total contributors: **1**
Task
----
- [2155: Bump doctrine/persistence](https://github.com/doctrine/mongodb-odm/pull/2155) thanks to @malarzm
=> Merge release 2.0.5 into master

docs/en/reference/introduction.rst
=> Typo in introduction

docs/en/reference/embedded-mapping.rst
| Fixed issues | NO
You forgot add example of embedded document in XML schema
=> Add embedded-document in Embedded Mapping documentation

tests/Doctrine/ODM/MongoDB/Tests/Functional/ReadPreferenceTest.php
Release [1.3.7](https://github.com/doctrine/mongodb-odm/milestone/57)
1.3.7
=====
- Total issues resolved: **0**
- Total pull requests resolved: **4**
- Total contributors: **4**
Bug
---
- [2172: Alias for Lookup with Relationship](https://github.com/doctrine/mongodb-odm/pull/2172) thanks to @josemiguelq
Documentation
-------------
- [2164: Chaged the Text Search docs on language](https://github.com/doctrine/mongodb-odm/pull/2164) thanks to @Alfro
- [2158: Typo in introduction](https://github.com/doctrine/mongodb-odm/pull/2158) thanks to @solcik
Task
----
- [2159: Deprecation and forward compat for flush](https://github.com/doctrine/mongodb-odm/pull/2159) thanks to @malarzm
=> Merge release 1.3.7 into 2.0.x

composer.json, lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php, lib/Doctrine/ODM/MongoDB/UnitOfWork.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/TypedPropertiesTest.php, tests/Documents74/TypedDocument.php, tests/Documents74/TypedEmbeddedDocument.php
=> Typed properties support

lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
| Type         | cs
| Fixed issues | N/A
Following https://github.com/doctrine/mongodb-odm/pull/2189.
Better algorithm for `convertToDatabaseValue`.
=> Better `convertToDatabaseValue`

.scrutinizer.yml, .travis.yml, README.markdown
=> Coverage with codecov

lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/ShardCommand.php
| BC Break     | yes/no
| Fixed issues | doctrine/DoctrineMongoDBBundle#639
see issue details
=> Add missing parent::configure() call

lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
This PR cherry-picks part of #2234 to make PHPStan happy in 2.1.x branch.
=> Assert array value is an instance of the key 

lib/Doctrine/ODM/MongoDB/PersistentCollection/DefaultPersistentCollectionGenerator.php, tests/Doctrine/ODM/MongoDB/Tests/Functional/CustomCollectionsTest.php
=> Handle void return type in custom collection's methods

lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php, tests/Doctrine/ODM/MongoDB/Tests/DocumentRepositoryTest.php
#2228 rebased atop current master and squashed. Let's see if the build is green after that
=> add sort param to findOneBy with test

.doctrine-project.json
As per title + marks 1.3 as not maintained
=> Reflect 2.2 release on the website
